
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May 23 2026 02:46:43 IST (May 22 2026 21:16:43 UTC)

// Verification Directory fv/spi_master 

module spi_master(clk, rst, ext_spi_clkx2, start_trans, busy, MOSI,
     MISO, SCLK, CS, tx_data, rx_data, chipADDRS, transaction_length,
     CPOL, CPHA, default_val);
  input clk, rst, ext_spi_clkx2, start_trans, MISO, CPOL, CPHA,
       default_val;
  input [31:0] tx_data;
  input [2:0] chipADDRS;
  input [1:0] transaction_length;
  output busy, MOSI, SCLK;
  output [7:0] CS;
  output [31:0] rx_data;
  wire clk, rst, ext_spi_clkx2, start_trans, MISO, CPOL, CPHA,
       default_val;
  wire [31:0] tx_data;
  wire [2:0] chipADDRS;
  wire [1:0] transaction_length;
  wire busy, MOSI, SCLK;
  wire [7:0] CS;
  wire [31:0] rx_data;
  wire [31:0] rx_buff;
  wire [32:0] tx_buff;
  wire [4:0] SPI_transaction_counter;
  wire [1:0] SPI_state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_94, n_95, n_96, n_97, n_98;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_137, spi_clk_main;
  OAI211D0 g4329__2398(.A1 (transaction_length[0]), .A2 (n_129), .B
       (n_135), .C (n_137), .ZN (MOSI));
  IND4D0 g4330__5107(.A1 (n_134), .B1 (CPHA), .B2
       (transaction_length[0]), .B3 (busy), .ZN (n_137));
  AOI31D0 g4331__6260(.A1 (n_132), .A2 (n_128), .A3
       (transaction_length[0]), .B (n_126), .ZN (n_135));
  SDFQD0 \rx_data_reg[31] (.CP (clk), .D (rx_buff[31]), .SI
       (rx_data[31]), .SE (n_133), .Q (rx_data[31]));
  MUX2ND0 g4333__4319(.I0 (tx_buff[16]), .I1 (tx_buff[32]), .S
       (transaction_length[1]), .ZN (n_134));
  SDFQD0 \rx_data_reg[30] (.CP (clk), .D (rx_buff[30]), .SI
       (rx_data[30]), .SE (n_133), .Q (rx_data[30]));
  MUX2D0 g4335__8428(.I0 (tx_buff[15]), .I1 (tx_buff[31]), .S
       (transaction_length[1]), .Z (n_132));
  DFCSNQD1 \tx_buff_reg[32] (.CDN (n_51), .SDN (n_14), .CP (n_131), .D
       (tx_buff[31]), .Q (tx_buff[32]));
  SDFQD0 \rx_data_reg[29] (.CP (clk), .D (rx_buff[29]), .SI
       (rx_data[29]), .SE (n_133), .Q (rx_data[29]));
  DFCNQD1 \rx_buff_reg[31] (.CDN (busy), .CP (n_130), .D (rx_buff[30]),
       .Q (rx_buff[31]));
  DFCSNQD1 \tx_buff_reg[31] (.CDN (n_87), .SDN (n_10), .CP (n_131), .D
       (tx_buff[30]), .Q (tx_buff[31]));
  SDFQD0 \rx_data_reg[28] (.CP (clk), .D (rx_buff[28]), .SI
       (rx_data[28]), .SE (n_133), .Q (rx_data[28]));
  DFCNQD1 \rx_buff_reg[30] (.CDN (busy), .CP (n_130), .D (rx_buff[29]),
       .Q (rx_buff[30]));
  DFCSNQD1 \tx_buff_reg[30] (.CDN (n_61), .SDN (n_23), .CP (n_131), .D
       (tx_buff[29]), .Q (tx_buff[30]));
  SDFQD0 \rx_data_reg[27] (.CP (clk), .D (rx_buff[27]), .SI
       (rx_data[27]), .SE (n_133), .Q (rx_data[27]));
  DFCNQD1 \rx_buff_reg[29] (.CDN (busy), .CP (n_130), .D (rx_buff[28]),
       .Q (rx_buff[29]));
  DFCSNQD1 \tx_buff_reg[29] (.CDN (n_85), .SDN (n_56), .CP (n_131), .D
       (tx_buff[28]), .Q (tx_buff[29]));
  SDFQD0 \rx_data_reg[26] (.CP (clk), .D (rx_buff[26]), .SI
       (rx_data[26]), .SE (n_133), .Q (rx_data[26]));
  DFCNQD1 \rx_buff_reg[28] (.CDN (busy), .CP (n_130), .D (rx_buff[27]),
       .Q (rx_buff[28]));
  DFCSNQD1 \tx_buff_reg[28] (.CDN (n_62), .SDN (n_13), .CP (n_131), .D
       (tx_buff[27]), .Q (tx_buff[28]));
  SDFQD0 \rx_data_reg[25] (.CP (clk), .D (rx_buff[25]), .SI
       (rx_data[25]), .SE (n_133), .Q (rx_data[25]));
  AOI33D0 g4346__5526(.A1 (busy), .A2 (n_127), .A3 (CPHA), .B1
       (tx_buff[23]), .B2 (transaction_length[1]), .B3 (n_128), .ZN
       (n_129));
  DFCNQD1 \rx_buff_reg[27] (.CDN (busy), .CP (n_130), .D (rx_buff[26]),
       .Q (rx_buff[27]));
  DFCSNQD1 \tx_buff_reg[27] (.CDN (n_63), .SDN (n_36), .CP (n_131), .D
       (tx_buff[26]), .Q (tx_buff[27]));
  SDFQD0 \rx_data_reg[24] (.CP (clk), .D (rx_buff[24]), .SI
       (rx_data[24]), .SE (n_133), .Q (rx_data[24]));
  DFCNQD1 \rx_buff_reg[26] (.CDN (busy), .CP (n_130), .D (rx_buff[25]),
       .Q (rx_buff[26]));
  DFCSNQD1 \tx_buff_reg[26] (.CDN (n_84), .SDN (n_37), .CP (n_131), .D
       (tx_buff[25]), .Q (tx_buff[26]));
  SDFQD0 \rx_data_reg[23] (.CP (clk), .D (rx_buff[23]), .SI
       (rx_data[23]), .SE (n_133), .Q (rx_data[23]));
  MUX2D0 g4356__6783(.I0 (tx_buff[8]), .I1 (tx_buff[24]), .S
       (transaction_length[1]), .Z (n_127));
  DFCNQD1 \rx_buff_reg[25] (.CDN (busy), .CP (n_130), .D (rx_buff[24]),
       .Q (rx_buff[25]));
  DFCSNQD1 \tx_buff_reg[25] (.CDN (n_67), .SDN (n_49), .CP (n_131), .D
       (tx_buff[24]), .Q (tx_buff[25]));
  SDFQD0 \rx_data_reg[22] (.CP (clk), .D (rx_buff[22]), .SI
       (rx_data[22]), .SE (n_133), .Q (rx_data[22]));
  DFCNQD1 \rx_buff_reg[24] (.CDN (busy), .CP (n_130), .D (rx_buff[23]),
       .Q (rx_buff[24]));
  DFCSNQD1 \tx_buff_reg[24] (.CDN (n_72), .SDN (n_22), .CP (n_131), .D
       (tx_buff[23]), .Q (tx_buff[24]));
  SDFQD0 \rx_data_reg[21] (.CP (clk), .D (rx_buff[21]), .SI
       (rx_data[21]), .SE (n_133), .Q (rx_data[21]));
  DFCNQD1 \rx_buff_reg[23] (.CDN (busy), .CP (n_130), .D (rx_buff[22]),
       .Q (rx_buff[23]));
  DFCSNQD1 \tx_buff_reg[23] (.CDN (n_83), .SDN (n_18), .CP (n_131), .D
       (tx_buff[22]), .Q (tx_buff[23]));
  SDFQD0 \rx_data_reg[20] (.CP (clk), .D (rx_buff[20]), .SI
       (rx_data[20]), .SE (n_133), .Q (rx_data[20]));
  DFCNQD1 \rx_buff_reg[22] (.CDN (busy), .CP (n_130), .D (rx_buff[21]),
       .Q (rx_buff[22]));
  DFCSNQD1 \tx_buff_reg[22] (.CDN (n_79), .SDN (n_38), .CP (n_131), .D
       (tx_buff[21]), .Q (tx_buff[22]));
  SDFQD0 \rx_data_reg[19] (.CP (clk), .D (rx_buff[19]), .SI
       (rx_data[19]), .SE (n_133), .Q (rx_data[19]));
  DFCNQD1 \rx_buff_reg[21] (.CDN (busy), .CP (n_130), .D (rx_buff[20]),
       .Q (rx_buff[21]));
  DFCSNQD1 \tx_buff_reg[21] (.CDN (n_64), .SDN (n_39), .CP (n_131), .D
       (tx_buff[20]), .Q (tx_buff[21]));
  DFCNQD1 \rx_buff_reg[20] (.CDN (busy), .CP (n_130), .D (rx_buff[19]),
       .Q (rx_buff[20]));
  SDFQD0 \rx_data_reg[18] (.CP (clk), .D (rx_buff[18]), .SI
       (rx_data[18]), .SE (n_133), .Q (rx_data[18]));
  DFCSNQD1 \tx_buff_reg[20] (.CDN (n_94), .SDN (n_16), .CP (n_131), .D
       (tx_buff[19]), .Q (tx_buff[20]));
  SDFQD0 \rx_data_reg[17] (.CP (clk), .D (rx_buff[17]), .SI
       (rx_data[17]), .SE (n_133), .Q (rx_data[17]));
  DFCNQD1 \rx_buff_reg[19] (.CDN (busy), .CP (n_130), .D (rx_buff[18]),
       .Q (rx_buff[19]));
  DFCSNQD1 \tx_buff_reg[19] (.CDN (n_88), .SDN (n_28), .CP (n_131), .D
       (tx_buff[18]), .Q (tx_buff[19]));
  SDFQD0 \rx_data_reg[16] (.CP (clk), .D (rx_buff[16]), .SI
       (rx_data[16]), .SE (n_133), .Q (rx_data[16]));
  DFCNQD1 \rx_buff_reg[18] (.CDN (busy), .CP (n_130), .D (rx_buff[17]),
       .Q (rx_buff[18]));
  DFCSNQD1 \tx_buff_reg[18] (.CDN (n_66), .SDN (n_59), .CP (n_131), .D
       (tx_buff[17]), .Q (tx_buff[18]));
  SDFQD0 \rx_data_reg[15] (.CP (clk), .D (rx_buff[15]), .SI
       (rx_data[15]), .SE (n_133), .Q (rx_data[15]));
  DFCNQD1 \rx_buff_reg[17] (.CDN (busy), .CP (n_130), .D (rx_buff[16]),
       .Q (rx_buff[17]));
  DFCSNQD1 \tx_buff_reg[17] (.CDN (n_93), .SDN (n_45), .CP (n_131), .D
       (tx_buff[16]), .Q (tx_buff[17]));
  SDFQD0 \rx_data_reg[14] (.CP (clk), .D (rx_buff[14]), .SI
       (rx_data[14]), .SE (n_133), .Q (rx_data[14]));
  DFCNQD1 \rx_buff_reg[16] (.CDN (busy), .CP (n_130), .D (rx_buff[15]),
       .Q (rx_buff[16]));
  DFCSNQD1 \tx_buff_reg[16] (.CDN (n_78), .SDN (n_34), .CP (n_131), .D
       (tx_buff[15]), .Q (tx_buff[16]));
  SDFQD0 \rx_data_reg[13] (.CP (clk), .D (rx_buff[13]), .SI
       (rx_data[13]), .SE (n_133), .Q (rx_data[13]));
  DFCNQD1 \rx_buff_reg[15] (.CDN (busy), .CP (n_130), .D (rx_buff[14]),
       .Q (rx_buff[15]));
  DFCSNQD1 \tx_buff_reg[15] (.CDN (n_68), .SDN (n_21), .CP (n_131), .D
       (tx_buff[14]), .Q (tx_buff[15]));
  SDFQD0 \rx_data_reg[12] (.CP (clk), .D (rx_buff[12]), .SI
       (rx_data[12]), .SE (n_133), .Q (rx_data[12]));
  DFCNQD1 \rx_buff_reg[14] (.CDN (busy), .CP (n_130), .D (rx_buff[13]),
       .Q (rx_buff[14]));
  DFCSNQD1 \tx_buff_reg[14] (.CDN (n_82), .SDN (n_17), .CP (n_131), .D
       (tx_buff[13]), .Q (tx_buff[14]));
  SDFQD0 \rx_data_reg[11] (.CP (clk), .D (rx_buff[11]), .SI
       (rx_data[11]), .SE (n_133), .Q (rx_data[11]));
  DFCNQD1 \rx_buff_reg[13] (.CDN (busy), .CP (n_130), .D (rx_buff[12]),
       .Q (rx_buff[13]));
  DFCSNQD1 \tx_buff_reg[13] (.CDN (n_65), .SDN (n_40), .CP (n_131), .D
       (tx_buff[12]), .Q (tx_buff[13]));
  SDFQD0 \rx_data_reg[10] (.CP (clk), .D (rx_buff[10]), .SI
       (rx_data[10]), .SE (n_133), .Q (rx_data[10]));
  DFCNQD1 \rx_buff_reg[12] (.CDN (busy), .CP (n_130), .D (rx_buff[11]),
       .Q (rx_buff[12]));
  DFCSNQD1 \tx_buff_reg[12] (.CDN (n_92), .SDN (n_27), .CP (n_131), .D
       (tx_buff[11]), .Q (tx_buff[12]));
  SDFQD0 \rx_data_reg[9] (.CP (clk), .D (rx_buff[9]), .SI (rx_data[9]),
       .SE (n_133), .Q (rx_data[9]));
  DFCNQD1 \rx_buff_reg[11] (.CDN (busy), .CP (n_130), .D (rx_buff[10]),
       .Q (rx_buff[11]));
  DFCSNQD1 \tx_buff_reg[11] (.CDN (n_80), .SDN (n_33), .CP (n_131), .D
       (tx_buff[10]), .Q (tx_buff[11]));
  SDFQD0 \rx_data_reg[8] (.CP (clk), .D (rx_buff[8]), .SI (rx_data[8]),
       .SE (n_133), .Q (rx_data[8]));
  DFCNQD1 \rx_buff_reg[10] (.CDN (busy), .CP (n_130), .D (rx_buff[9]),
       .Q (rx_buff[10]));
  OAI32D0 g4403__3680(.A1 (transaction_length[0]), .A2
       (transaction_length[1]), .A3 (n_125), .B1 (n_50), .B2 (busy),
       .ZN (n_126));
  DFCSNQD1 \tx_buff_reg[10] (.CDN (n_69), .SDN (n_47), .CP (n_131), .D
       (tx_buff[9]), .Q (tx_buff[10]));
  SDFQD0 \rx_data_reg[7] (.CP (clk), .D (rx_buff[7]), .SI (rx_data[7]),
       .SE (n_133), .Q (rx_data[7]));
  DFCNQD1 \rx_buff_reg[9] (.CDN (busy), .CP (n_130), .D (rx_buff[8]),
       .Q (rx_buff[9]));
  DFCSNQD1 \tx_buff_reg[9] (.CDN (n_90), .SDN (n_41), .CP (n_131), .D
       (tx_buff[8]), .Q (tx_buff[9]));
  SDFQD0 \rx_data_reg[6] (.CP (clk), .D (rx_buff[6]), .SI (rx_data[6]),
       .SE (n_133), .Q (rx_data[6]));
  DFCNQD1 \rx_buff_reg[8] (.CDN (busy), .CP (n_130), .D (rx_buff[7]),
       .Q (rx_buff[8]));
  DFCSNQD1 \tx_buff_reg[8] (.CDN (n_89), .SDN (n_52), .CP (n_131), .D
       (tx_buff[7]), .Q (tx_buff[8]));
  CKND2D0 g4415__1617(.A1 (tx_buff[7]), .A2 (n_128), .ZN (n_125));
  DFCNQD1 \rx_buff_reg[7] (.CDN (busy), .CP (n_130), .D (rx_buff[6]),
       .Q (rx_buff[7]));
  SDFQD0 \rx_data_reg[5] (.CP (clk), .D (rx_buff[5]), .SI (rx_data[5]),
       .SE (n_133), .Q (rx_data[5]));
  DFCSNQD1 \tx_buff_reg[7] (.CDN (n_81), .SDN (n_29), .CP (n_131), .D
       (tx_buff[6]), .Q (tx_buff[7]));
  DFCNQD1 \rx_buff_reg[6] (.CDN (busy), .CP (n_130), .D (rx_buff[5]),
       .Q (rx_buff[6]));
  SDFQD0 \rx_data_reg[4] (.CP (clk), .D (rx_buff[4]), .SI (rx_data[4]),
       .SE (n_133), .Q (rx_data[4]));
  DFCSNQD1 \tx_buff_reg[6] (.CDN (n_70), .SDN (n_30), .CP (n_131), .D
       (tx_buff[5]), .Q (tx_buff[6]));
  DFCNQD1 \rx_buff_reg[5] (.CDN (busy), .CP (n_130), .D (rx_buff[4]),
       .Q (rx_buff[5]));
  SDFQD0 \rx_data_reg[3] (.CP (clk), .D (rx_buff[3]), .SI (rx_data[3]),
       .SE (n_133), .Q (rx_data[3]));
  DFCSNQD1 \tx_buff_reg[5] (.CDN (n_71), .SDN (n_42), .CP (n_131), .D
       (tx_buff[4]), .Q (tx_buff[5]));
  SDFQD0 \rx_data_reg[2] (.CP (clk), .D (rx_buff[2]), .SI (rx_data[2]),
       .SE (n_133), .Q (rx_data[2]));
  DFCNQD1 \rx_buff_reg[4] (.CDN (busy), .CP (n_130), .D (rx_buff[3]),
       .Q (rx_buff[4]));
  DFCSNQD1 \tx_buff_reg[4] (.CDN (n_73), .SDN (n_43), .CP (n_131), .D
       (tx_buff[3]), .Q (tx_buff[4]));
  DFNCSND1 \SPI_transaction_counter_reg[4] (.CDN (n_48), .SDN (n_35),
       .CPN (ext_spi_clkx2), .D (n_124), .Q
       (SPI_transaction_counter[4]), .QN (UNCONNECTED));
  SDFQD0 \rx_data_reg[1] (.CP (clk), .D (rx_buff[1]), .SI (rx_data[1]),
       .SE (n_133), .Q (rx_data[1]));
  DFCNQD1 \rx_buff_reg[3] (.CDN (busy), .CP (n_130), .D (rx_buff[2]),
       .Q (rx_buff[3]));
  DFNCSND1 \SPI_transaction_counter_reg[3] (.CDN (n_12), .SDN (n_11),
       .CPN (ext_spi_clkx2), .D (n_122), .Q
       (SPI_transaction_counter[3]), .QN (UNCONNECTED0));
  DFCSNQD1 \tx_buff_reg[3] (.CDN (n_77), .SDN (n_19), .CP (n_131), .D
       (tx_buff[2]), .Q (tx_buff[3]));
  MOAI22D0 g4404__2802(.A1 (n_123), .A2 (SPI_transaction_counter[4]),
       .B1 (n_123), .B2 (SPI_transaction_counter[4]), .ZN (n_124));
  SDFQD0 \rx_data_reg[0] (.CP (clk), .D (rx_buff[0]), .SI (rx_data[0]),
       .SE (n_133), .Q (rx_data[0]));
  DFNCND1 \SPI_transaction_counter_reg[2] (.CDN (n_119), .CPN
       (ext_spi_clkx2), .D (n_121), .Q (SPI_transaction_counter[2]),
       .QN (UNCONNECTED1));
  OA21D0 g4416__1705(.A1 (n_120), .A2 (SPI_transaction_counter[3]), .B
       (n_123), .Z (n_122));
  DFCNQD1 \rx_buff_reg[2] (.CDN (busy), .CP (n_130), .D (rx_buff[1]),
       .Q (rx_buff[2]));
  DFCSNQD1 \tx_buff_reg[2] (.CDN (n_86), .SDN (n_53), .CP (n_131), .D
       (tx_buff[1]), .Q (tx_buff[2]));
  IAO21D0 g4428__5122(.A1 (n_116), .A2 (SPI_transaction_counter[2]), .B
       (n_120), .ZN (n_121));
  CKND2D0 g4422__8246(.A1 (n_120), .A2 (SPI_transaction_counter[3]),
       .ZN (n_123));
  DFQD1 \CS_reg[5] (.CP (clk), .D (n_115), .Q (CS[5]));
  DFCNQD1 \rx_buff_reg[1] (.CDN (busy), .CP (n_130), .D (rx_buff[0]),
       .Q (rx_buff[1]));
  DFNCND1 \SPI_transaction_counter_reg[1] (.CDN (n_119), .CPN
       (ext_spi_clkx2), .D (n_117), .Q (SPI_transaction_counter[1]),
       .QN (UNCONNECTED2));
  DFQD1 \CS_reg[1] (.CP (clk), .D (n_110), .Q (CS[1]));
  DFQD1 \CS_reg[0] (.CP (clk), .D (n_112), .Q (CS[0]));
  DFQD1 \CS_reg[2] (.CP (clk), .D (n_107), .Q (CS[2]));
  DFQD1 \CS_reg[4] (.CP (clk), .D (n_103), .Q (CS[4]));
  OAI32D1 g4434__7098(.A1 (n_25), .A2 (n_97), .A3 (n_24), .B1 (n_114),
       .B2 (n_26), .ZN (n_118));
  DFCSNQD1 \tx_buff_reg[1] (.CDN (n_76), .SDN (n_54), .CP (n_131), .D
       (tx_buff[0]), .Q (tx_buff[1]));
  DFQD1 \CS_reg[3] (.CP (clk), .D (n_109), .Q (CS[3]));
  DFQD1 \CS_reg[7] (.CP (clk), .D (n_113), .Q (CS[7]));
  DFQD1 \CS_reg[6] (.CP (clk), .D (n_104), .Q (CS[6]));
  IAO21D0 g4445__6131(.A1 (n_101), .A2 (SPI_transaction_counter[1]), .B
       (n_116), .ZN (n_117));
  CKAN2D1 g4436__1881(.A1 (n_116), .A2 (SPI_transaction_counter[2]), .Z
       (n_120));
  AO211D1 g4461__5115(.A1 (n_8), .A2 (n_111), .B (n_60), .C (n_114), .Z
       (n_115));
  DFCNQD1 \rx_buff_reg[0] (.CDN (busy), .CP (n_130), .D (MISO), .Q
       (rx_buff[0]));
  DFNCND1 \SPI_transaction_counter_reg[0] (.CDN (n_119), .CPN
       (ext_spi_clkx2), .D (n_100), .Q (SPI_transaction_counter[0]),
       .QN (UNCONNECTED3));
  OAI211D1 g4457__7482(.A1 (n_6), .A2 (n_74), .B (n_75), .C (n_96), .ZN
       (n_113));
  AO221D0 g4453__4733(.A1 (n_106), .A2 (n_111), .B1 (CS[0]), .B2
       (n_32), .C (n_114), .Z (n_112));
  AO221D0 g4452__6161(.A1 (n_108), .A2 (n_111), .B1 (CS[1]), .B2
       (n_15), .C (n_114), .Z (n_110));
  AO221D0 g4458__9315(.A1 (n_108), .A2 (n_105), .B1 (CS[3]), .B2
       (n_46), .C (n_114), .Z (n_109));
  AO221D0 g4463__9945(.A1 (n_106), .A2 (n_105), .B1 (CS[2]), .B2
       (n_58), .C (n_114), .Z (n_107));
  AO221D0 g4460__2883(.A1 (n_102), .A2 (n_105), .B1 (CS[6]), .B2
       (n_57), .C (n_114), .Z (n_104));
  AO221D0 g4459__2346(.A1 (n_102), .A2 (n_111), .B1 (CS[4]), .B2
       (n_20), .C (n_114), .Z (n_103));
  DFCSNQD1 \tx_buff_reg[0] (.CDN (n_91), .SDN (n_44), .CP (n_131), .D
       (default_val), .Q (tx_buff[0]));
  CKAN2D1 g4455__1666(.A1 (n_101), .A2 (SPI_transaction_counter[1]), .Z
       (n_116));
  IAO21D0 g4470__7410(.A1 (n_98), .A2 (SPI_transaction_counter[0]), .B
       (n_101), .ZN (n_100));
  CKND0 g4469(.I (n_131), .ZN (n_130));
  MUX2ND0 g4471__6417(.I0 (n_95), .I1 (n_98), .S (CPOL), .ZN (SCLK));
  DFKCNQD1 \SPI_state_reg[1] (.CP (clk), .CN (n_7), .D (SPI_state[0]),
       .Q (SPI_state[1]));
  INR4D0 g4462__5477(.A1 (ext_spi_clkx2), .B1
       (SPI_transaction_counter[3]), .B2 (n_98), .B3 (n_5), .ZN (n_97));
  INVD1 g4482(.I (n_96), .ZN (n_114));
  MUX2ND0 g4472__2398(.I0 (n_98), .I1 (n_95), .S (CPHA), .ZN (n_131));
  OR2D0 g4498__5107(.A1 (n_119), .A2 (tx_data[20]), .Z (n_94));
  OR2D0 g4483__6260(.A1 (n_119), .A2 (tx_data[17]), .Z (n_93));
  OR2D0 g4484__4319(.A1 (n_119), .A2 (tx_data[12]), .Z (n_92));
  OR2D0 g4486__8428(.A1 (n_119), .A2 (tx_data[0]), .Z (n_91));
  OR2D0 g4488__5526(.A1 (n_119), .A2 (tx_data[9]), .Z (n_90));
  OR2D0 g4491__6783(.A1 (n_119), .A2 (tx_data[8]), .Z (n_89));
  OR2D0 g4492__3680(.A1 (n_119), .A2 (tx_data[19]), .Z (n_88));
  OR2D0 g4495__1617(.A1 (n_119), .A2 (tx_data[31]), .Z (n_87));
  OR2D0 g4496__2802(.A1 (n_119), .A2 (tx_data[2]), .Z (n_86));
  OR2D0 g4513__1705(.A1 (n_119), .A2 (tx_data[29]), .Z (n_85));
  OR2D0 g4499__5122(.A1 (n_119), .A2 (tx_data[26]), .Z (n_84));
  OR2D0 g4502__8246(.A1 (n_119), .A2 (tx_data[23]), .Z (n_83));
  OR2D0 g4504__7098(.A1 (n_119), .A2 (tx_data[14]), .Z (n_82));
  OR2D0 g4507__6131(.A1 (n_119), .A2 (tx_data[7]), .Z (n_81));
  OR2D0 g4509__1881(.A1 (n_119), .A2 (tx_data[11]), .Z (n_80));
  OR2D0 g4511__5115(.A1 (n_119), .A2 (tx_data[22]), .Z (n_79));
  OR2D0 g4512__7482(.A1 (n_119), .A2 (tx_data[16]), .Z (n_78));
  CKAN2D1 g4476__4733(.A1 (n_98), .A2 (SPI_transaction_counter[0]), .Z
       (n_101));
  OR2D0 g4539__6161(.A1 (n_119), .A2 (tx_data[3]), .Z (n_77));
  OR2D0 g4520__9315(.A1 (n_119), .A2 (tx_data[1]), .Z (n_76));
  OAI21D1 g4467__9945(.A1 (n_74), .A2 (n_31), .B (CS[7]), .ZN (n_75));
  OR2D0 g4525__2883(.A1 (n_119), .A2 (tx_data[4]), .Z (n_73));
  OR2D0 g4526__2346(.A1 (n_119), .A2 (tx_data[24]), .Z (n_72));
  OR2D0 g4527__1666(.A1 (n_119), .A2 (tx_data[5]), .Z (n_71));
  OR2D0 g4529__7410(.A1 (n_119), .A2 (tx_data[6]), .Z (n_70));
  OR2D0 g4531__6417(.A1 (n_119), .A2 (tx_data[10]), .Z (n_69));
  OR2D0 g4536__5477(.A1 (n_119), .A2 (tx_data[15]), .Z (n_68));
  OR2D0 g4516__2398(.A1 (n_119), .A2 (tx_data[25]), .Z (n_67));
  OR2D0 g4540__5107(.A1 (n_119), .A2 (tx_data[18]), .Z (n_66));
  OR2D0 g4541__6260(.A1 (n_119), .A2 (tx_data[13]), .Z (n_65));
  OR2D0 g4542__4319(.A1 (n_119), .A2 (tx_data[21]), .Z (n_64));
  OR2D0 g4547__8428(.A1 (n_119), .A2 (tx_data[27]), .Z (n_63));
  OR2D0 g4548__5526(.A1 (n_119), .A2 (tx_data[28]), .Z (n_62));
  OR2D0 g4549__6783(.A1 (n_119), .A2 (tx_data[30]), .Z (n_61));
  OA21D1 g4466__3680(.A1 (n_74), .A2 (chipADDRS[1]), .B (CS[5]), .Z
       (n_60));
  NR2XD0 g4521__1617(.A1 (n_9), .A2 (rst), .ZN (n_96));
  CKND2D0 g4500__2802(.A1 (n_55), .A2 (tx_data[18]), .ZN (n_59));
  CKND2D1 g4474__1705(.A1 (n_106), .A2 (chipADDRS[1]), .ZN (n_58));
  CKND2D1 g4475__5122(.A1 (n_102), .A2 (chipADDRS[1]), .ZN (n_57));
  CKND2D0 g4485__8246(.A1 (n_55), .A2 (tx_data[29]), .ZN (n_56));
  CKND2D0 g4487__7098(.A1 (n_55), .A2 (tx_data[1]), .ZN (n_54));
  CKND2D0 g4489__6131(.A1 (n_55), .A2 (tx_data[2]), .ZN (n_53));
  CKND2D0 g4490__1881(.A1 (n_55), .A2 (tx_data[8]), .ZN (n_52));
  CKND2D0 g4493__5115(.A1 (n_55), .A2 (n_50), .ZN (n_51));
  CKND2D0 g4494__7482(.A1 (n_55), .A2 (tx_data[25]), .ZN (n_49));
  CKND2D0 g4555__4733(.A1 (n_55), .A2 (transaction_length[1]), .ZN
       (n_48));
  CKND2D0 g4497__6161(.A1 (n_55), .A2 (tx_data[10]), .ZN (n_47));
  CKND2D1 g4473__9315(.A1 (n_108), .A2 (chipADDRS[1]), .ZN (n_46));
  CKND2D0 g4501__9945(.A1 (n_55), .A2 (tx_data[17]), .ZN (n_45));
  CKND2D0 g4503__2883(.A1 (n_55), .A2 (tx_data[0]), .ZN (n_44));
  CKND2D0 g4505__2346(.A1 (n_55), .A2 (tx_data[4]), .ZN (n_43));
  CKND2D0 g4506__1666(.A1 (n_55), .A2 (tx_data[5]), .ZN (n_42));
  CKND2D0 g4508__7410(.A1 (n_55), .A2 (tx_data[9]), .ZN (n_41));
  CKND2D0 g4510__6417(.A1 (n_55), .A2 (tx_data[13]), .ZN (n_40));
  CKND2D0 g4514__5477(.A1 (n_55), .A2 (tx_data[21]), .ZN (n_39));
  CKND2D0 g4515__2398(.A1 (n_55), .A2 (tx_data[22]), .ZN (n_38));
  CKND2D0 g4517__5107(.A1 (n_55), .A2 (tx_data[26]), .ZN (n_37));
  CKND2D0 g4518__6260(.A1 (n_55), .A2 (tx_data[27]), .ZN (n_36));
  CKND2D0 g4556__4319(.A1 (n_55), .A2 (n_0), .ZN (n_35));
  CKND2D0 g4538__8428(.A1 (n_55), .A2 (tx_data[16]), .ZN (n_34));
  CKND2D0 g4524__5526(.A1 (n_55), .A2 (tx_data[11]), .ZN (n_33));
  CKND2D1 g4479__6783(.A1 (n_106), .A2 (n_31), .ZN (n_32));
  CKND2D0 g4528__3680(.A1 (n_55), .A2 (tx_data[6]), .ZN (n_30));
  CKND2D0 g4530__1617(.A1 (n_55), .A2 (tx_data[7]), .ZN (n_29));
  CKND2D0 g4532__2802(.A1 (n_55), .A2 (tx_data[19]), .ZN (n_28));
  CKND2D0 g4533__1705(.A1 (n_55), .A2 (tx_data[12]), .ZN (n_27));
  AOI22D1 g4481__5122(.A1 (SPI_state[0]), .A2 (n_25), .B1 (n_24), .B2
       (start_trans), .ZN (n_26));
  CKND2D0 g4534__8246(.A1 (n_55), .A2 (tx_data[30]), .ZN (n_23));
  CKND2D0 g4535__7098(.A1 (n_55), .A2 (tx_data[24]), .ZN (n_22));
  CKND2D0 g4537__6131(.A1 (n_55), .A2 (tx_data[15]), .ZN (n_21));
  CKND2D1 g4477__1881(.A1 (n_102), .A2 (n_31), .ZN (n_20));
  CKND2D0 g4543__5115(.A1 (n_55), .A2 (tx_data[3]), .ZN (n_19));
  CKND2D0 g4544__7482(.A1 (n_55), .A2 (tx_data[23]), .ZN (n_18));
  CKND2D0 g4545__4733(.A1 (n_55), .A2 (tx_data[14]), .ZN (n_17));
  CKND2D0 g4546__6161(.A1 (n_55), .A2 (tx_data[20]), .ZN (n_16));
  CKND2D1 g4478__9315(.A1 (n_108), .A2 (n_31), .ZN (n_15));
  CKND2D0 g4550__9945(.A1 (n_55), .A2 (default_val), .ZN (n_14));
  CKND2D0 g4551__2883(.A1 (n_55), .A2 (tx_data[28]), .ZN (n_13));
  CKND2D0 g4553__2346(.A1 (n_55), .A2 (transaction_length[0]), .ZN
       (n_12));
  CKND2D0 g4554__1666(.A1 (n_55), .A2 (n_2), .ZN (n_11));
  CKND2D0 g4519__7410(.A1 (n_55), .A2 (tx_data[31]), .ZN (n_10));
  CKND1 g4568(.I (n_133), .ZN (n_9));
  CKND1 g4522(.I (n_74), .ZN (n_8));
  CKND0 g4569(.I (n_55), .ZN (n_119));
  OAI21D1 g4552__6417(.A1 (spi_clk_main), .A2 (rst), .B (n_25), .ZN
       (n_7));
  CKND0 g4566(.I (n_105), .ZN (n_6));
  NR2D0 g4557__5477(.A1 (n_4), .A2 (CPHA), .ZN (n_128));
  CKND1 g4523(.I (n_95), .ZN (n_98));
  NR3D0 g4558__2398(.A1 (SPI_state[0]), .A2 (chipADDRS[2]), .A3
       (chipADDRS[0]), .ZN (n_106));
  NR2D0 g4570__5107(.A1 (n_31), .A2 (start_trans), .ZN (n_105));
  ND3D1 g4559__6260(.A1 (n_24), .A2 (chipADDRS[2]), .A3 (chipADDRS[0]),
       .ZN (n_74));
  INR3D0 g4561__4319(.A1 (chipADDRS[2]), .B1 (chipADDRS[0]), .B2
       (SPI_state[0]), .ZN (n_102));
  OR4D0 g4480__8428(.A1 (SPI_transaction_counter[4]), .A2
       (SPI_transaction_counter[0]), .A3 (SPI_transaction_counter[1]),
       .A4 (SPI_transaction_counter[2]), .Z (n_5));
  ND3D1 g4562__5526(.A1 (SPI_state[0]), .A2 (SPI_state[1]), .A3
       (spi_clk_main), .ZN (n_95));
  INR3D0 g4560__6783(.A1 (chipADDRS[0]), .B1 (chipADDRS[2]), .B2
       (SPI_state[0]), .ZN (n_108));
  ND2D1 g4572__3680(.A1 (n_24), .A2 (SPI_state[1]), .ZN (n_133));
  CKND0 g4567(.I (n_4), .ZN (busy));
  NR2XD0 g4573__1617(.A1 (n_24), .A2 (SPI_state[1]), .ZN (n_55));
  NR2D0 g4571__2802(.A1 (SPI_state[0]), .A2 (SPI_state[1]), .ZN (n_4));
  IND2D1 g4564__1705(.A1 (rst), .B1 (SPI_state[1]), .ZN (n_25));
  NR2D0 g4565__5122(.A1 (start_trans), .A2 (chipADDRS[1]), .ZN (n_111));
  CKND0 g4574(.I (default_val), .ZN (n_50));
  CKND0 g4579(.I (transaction_length[0]), .ZN (n_2));
  CKND0 g4578(.I (rst), .ZN (n_1));
  CKND0 g4575(.I (transaction_length[1]), .ZN (n_0));
  CKND0 g4580(.I (chipADDRS[1]), .ZN (n_31));
  DFCND1 spi_clk_main_reg(.CDN (n_1), .CP (ext_spi_clkx2), .D (n_3), .Q
       (spi_clk_main), .QN (n_3));
  DFD1 \SPI_state_reg[0] (.CP (clk), .D (n_118), .Q (SPI_state[0]), .QN
       (n_24));
endmodule

