
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May 23 2026 02:45:21 IST (May 22 2026 21:15:21 UTC)

// Verification Directory fv/SPI_Master_1 

module SPI_Master_1(i_Rst_L, i_Clk, i_TX_Byte, i_TX_DV, o_TX_Ready,
     o_RX_DV, o_RX_Byte, o_SPI_Clk, i_SPI_MISO, o_SPI_MOSI);
  input i_Rst_L, i_Clk, i_TX_DV, i_SPI_MISO;
  input [7:0] i_TX_Byte;
  output o_TX_Ready, o_RX_DV, o_SPI_Clk, o_SPI_MOSI;
  output [7:0] o_RX_Byte;
  wire i_Rst_L, i_Clk, i_TX_DV, i_SPI_MISO;
  wire [7:0] i_TX_Byte;
  wire o_TX_Ready, o_RX_DV, o_SPI_Clk, o_SPI_MOSI;
  wire [7:0] o_RX_Byte;
  wire [2:0] r_TX_Bit_Count;
  wire [7:0] r_TX_Byte;
  wire [2:0] r_RX_Bit_Count;
  wire [4:0] r_SPI_Clk_Edges;
  wire [1:0] r_SPI_Clk_Count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_95, r_Leading_Edge, r_TX_DV, r_Trailing_Edge;
  IOA21D1 g2608__2398(.A1 (o_SPI_MOSI), .A2 (o_TX_Ready), .B (n_81),
       .ZN (n_82));
  DFSNQD1 \r_TX_Bit_Count_reg[2] (.SDN (i_Rst_L), .CP (i_Clk), .D
       (n_80), .Q (r_TX_Bit_Count[2]));
  AOI32D1 g2609__5107(.A1 (r_TX_Byte[7]), .A2 (n_46), .A3 (r_TX_DV),
       .B1 (n_74), .B2 (n_79), .ZN (n_81));
  DFCNQD1 \o_RX_Byte_reg[5] (.CDN (i_Rst_L), .CP (i_Clk), .D (n_75), .Q
       (o_RX_Byte[5]));
  DFCNQD1 \o_RX_Byte_reg[6] (.CDN (i_Rst_L), .CP (i_Clk), .D (n_77), .Q
       (o_RX_Byte[6]));
  DFCNQD1 \o_RX_Byte_reg[7] (.CDN (i_Rst_L), .CP (i_Clk), .D (n_78), .Q
       (o_RX_Byte[7]));
  DFCNQD1 \o_RX_Byte_reg[1] (.CDN (i_Rst_L), .CP (i_Clk), .D (n_65), .Q
       (o_RX_Byte[1]));
  DFCNQD1 \o_RX_Byte_reg[2] (.CDN (i_Rst_L), .CP (i_Clk), .D (n_68), .Q
       (o_RX_Byte[2]));
  OAI211D1 g2611__6260(.A1 (r_TX_Bit_Count[2]), .A2 (n_73), .B (n_57),
       .C (n_79), .ZN (n_80));
  DFCNQD1 \o_RX_Byte_reg[3] (.CDN (i_Rst_L), .CP (i_Clk), .D (n_71), .Q
       (o_RX_Byte[3]));
  DFCNQD1 \o_RX_Byte_reg[4] (.CDN (i_Rst_L), .CP (i_Clk), .D (n_69), .Q
       (o_RX_Byte[4]));
  OAI21D1 g2626__4319(.A1 (n_76), .A2 (n_70), .B (n_58), .ZN (n_78));
  SDFCNQD1 \o_RX_Byte_reg[0] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (i_SPI_MISO), .SI (o_RX_Byte[0]), .SE (n_56), .Q (o_RX_Byte[0]));
  OAI21D1 g2627__8428(.A1 (n_76), .A2 (n_66), .B (n_61), .ZN (n_77));
  OAI21D1 g2631__5526(.A1 (n_76), .A2 (n_64), .B (n_60), .ZN (n_75));
  OAI221D0 g2612__6783(.A1 (n_4), .A2 (n_73), .B1 (r_Trailing_Edge),
       .B2 (n_0), .C (n_63), .ZN (n_74));
  OAI211D1 g2615__3680(.A1 (n_52), .A2 (n_62), .B (n_73), .C (n_79),
       .ZN (n_72));
  OAI21D1 g2628__1617(.A1 (n_67), .A2 (n_70), .B (n_53), .ZN (n_71));
  MOAI22D1 g2629__2802(.A1 (n_76), .A2 (n_44), .B1 (n_54), .B2
       (o_RX_Byte[4]), .ZN (n_69));
  MOAI22D1 g2630__1705(.A1 (n_67), .A2 (n_66), .B1 (n_51), .B2
       (o_RX_Byte[2]), .ZN (n_68));
  MOAI22D1 g2632__5122(.A1 (n_67), .A2 (n_64), .B1 (n_50), .B2
       (o_RX_Byte[1]), .ZN (n_65));
  AOI33D1 g2621__8246(.A1 (n_13), .A2 (r_TX_Bit_Count[0]), .A3
       (r_Trailing_Edge), .B1 (n_2), .B2 (n_62), .B3
       (r_TX_Bit_Count[1]), .ZN (n_63));
  OAI21D1 g2637__7098(.A1 (n_59), .A2 (n_66), .B (o_RX_Byte[6]), .ZN
       (n_61));
  SDFSNQD1 \r_TX_Bit_Count_reg[0] (.SDN (i_Rst_L), .CP (i_Clk), .D
       (o_TX_Ready), .SI (n_40), .SE (n_79), .Q (r_TX_Bit_Count[0]));
  OAI21D1 g2638__6131(.A1 (n_59), .A2 (n_64), .B (o_RX_Byte[5]), .ZN
       (n_60));
  OAI21D1 g2640__1881(.A1 (n_59), .A2 (n_70), .B (o_RX_Byte[7]), .ZN
       (n_58));
  CKND2D1 g2614__5115(.A1 (n_73), .A2 (r_TX_Bit_Count[2]), .ZN (n_57));
  DFCNQD1 o_RX_DV_reg(.CDN (i_Rst_L), .CP (i_Clk), .D (n_55), .Q
       (o_RX_DV));
  CKND1 g2642(.I (n_55), .ZN (n_56));
  CKND2D1 g2643__7482(.A1 (n_48), .A2 (n_11), .ZN (n_54));
  OAI21D1 g2639__4733(.A1 (n_45), .A2 (n_70), .B (o_RX_Byte[3]), .ZN
       (n_53));
  CKND2D1 g2641__6161(.A1 (n_62), .A2 (n_52), .ZN (n_73));
  IND2D1 g2649__9315(.A1 (n_66), .B1 (n_49), .ZN (n_51));
  IND2D1 g2650__9945(.A1 (n_64), .B1 (n_49), .ZN (n_50));
  CKND2D1 g2644__2883(.A1 (n_49), .A2 (i_SPI_MISO), .ZN (n_67));
  CKND2D1 g2646__2346(.A1 (n_48), .A2 (i_SPI_MISO), .ZN (n_76));
  OAI211D1 g2648__1666(.A1 (r_Leading_Edge), .A2 (n_1), .B (n_38), .C
       (n_46), .ZN (n_47));
  NR2D1 g2645__7410(.A1 (n_45), .A2 (n_44), .ZN (n_55));
  OAI221D0 g2651__6417(.A1 (n_12), .A2 (n_41), .B1 (r_Leading_Edge),
       .B2 (n_39), .C (n_46), .ZN (n_43));
  OAI221D0 g2652__5477(.A1 (n_3), .A2 (r_Leading_Edge), .B1 (n_41), .B2
       (r_RX_Bit_Count[0]), .C (n_46), .ZN (n_42));
  INVD1 g2653(.I (n_48), .ZN (n_59));
  NR2D1 g2664__2398(.A1 (r_TX_Bit_Count[0]), .A2 (n_37), .ZN (n_62));
  DFCNQD1 \r_SPI_Clk_Edges_reg[4] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (n_34), .Q (r_SPI_Clk_Edges[4]));
  DFCNQD1 \r_SPI_Clk_Edges_reg[1] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (n_35), .Q (r_SPI_Clk_Edges[1]));
  CKXOR2D1 g2658__5107(.A1 (r_TX_Bit_Count[0]), .A2 (r_Trailing_Edge),
       .Z (n_40));
  CKND1 g2654(.I (n_45), .ZN (n_49));
  NR3D0 g2655__6260(.A1 (n_39), .A2 (n_41), .A3 (o_TX_Ready), .ZN
       (n_48));
  DFCNQD1 \r_SPI_Clk_Edges_reg[3] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (n_36), .Q (r_SPI_Clk_Edges[3]));
  DFCNQD1 r_SPI_Clk_reg(.CDN (i_Rst_L), .CP (i_Clk), .D (n_31), .Q
       (r_SPI_Clk_Count[1]));
  ND3D1 g2656__4319(.A1 (n_39), .A2 (n_46), .A3 (r_Leading_Edge), .ZN
       (n_45));
  DFCNQD1 \r_SPI_Clk_Edges_reg[0] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (n_33), .Q (r_SPI_Clk_Edges[0]));
  IOA21D1 g2663__8428(.A1 (n_44), .A2 (n_70), .B (r_Leading_Edge), .ZN
       (n_38));
  NR2XD0 g2669__5526(.A1 (n_26), .A2 (i_TX_DV), .ZN (n_36));
  NR2XD0 g2674__6783(.A1 (n_28), .A2 (i_TX_DV), .ZN (n_35));
  AO211D1 g2675__3680(.A1 (n_27), .A2 (r_SPI_Clk_Edges[4]), .B (n_95),
       .C (i_TX_DV), .Z (n_34));
  DFCNQD1 \r_SPI_Clk_Count_reg[0] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (n_29), .Q (r_SPI_Clk_Count[0]));
  NR2XD0 g2673__1617(.A1 (n_23), .A2 (i_TX_DV), .ZN (n_33));
  NR2XD0 g2672__2802(.A1 (n_22), .A2 (i_TX_DV), .ZN (n_32));
  MOAI22D1 g2657__1705(.A1 (n_30), .A2 (r_SPI_Clk_Count[1]), .B1
       (n_30), .B2 (r_SPI_Clk_Count[1]), .ZN (n_31));
  OA21D1 g2676__5122(.A1 (n_19), .A2 (r_SPI_Clk_Count[0]), .B (n_30),
       .Z (n_29));
  NR2XD0 g2679__8246(.A1 (r_TX_DV), .A2 (o_TX_Ready), .ZN (n_79));
  AOI22D1 g2680__7098(.A1 (n_25), .A2 (n_5), .B1 (n_27), .B2
       (r_SPI_Clk_Edges[1]), .ZN (n_28));
  AOI22D1 g2682__6131(.A1 (n_25), .A2 (n_15), .B1 (n_27), .B2
       (r_SPI_Clk_Edges[3]), .ZN (n_26));
  INR3D0 g2678__1881(.A1 (r_SPI_Clk_Count[1]), .B1 (i_TX_DV), .B2
       (n_27), .ZN (n_24));
  MAOI22D1 g2681__5115(.A1 (n_27), .A2 (r_SPI_Clk_Edges[0]), .B1
       (n_27), .B2 (r_SPI_Clk_Edges[0]), .ZN (n_23));
  MAOI22D1 g2683__7482(.A1 (n_27), .A2 (r_SPI_Clk_Edges[2]), .B1
       (n_27), .B2 (n_10), .ZN (n_22));
  NR3D0 g2677__6161(.A1 (n_27), .A2 (r_SPI_Clk_Count[1]), .A3
       (i_TX_DV), .ZN (n_20));
  ND2D1 g2687__9315(.A1 (n_19), .A2 (r_SPI_Clk_Count[0]), .ZN (n_30));
  INVD1 g2688(.I (n_27), .ZN (n_25));
  ND2D1 g2689__9945(.A1 (n_17), .A2 (r_SPI_Clk_Count[0]), .ZN (n_27));
  NR2XD0 g2690__2883(.A1 (n_17), .A2 (i_TX_DV), .ZN (n_18));
  INR2D1 g2691__2346(.A1 (n_17), .B1 (i_TX_DV), .ZN (n_19));
  IND2D1 g2692__1666(.A1 (r_SPI_Clk_Edges[4]), .B1 (n_16), .ZN (n_17));
  MOAI22D1 g2693__7410(.A1 (n_14), .A2 (r_SPI_Clk_Edges[3]), .B1
       (n_14), .B2 (r_SPI_Clk_Edges[3]), .ZN (n_15));
  MUX2ND0 g2697__6417(.I0 (n_8), .I1 (n_9), .S (r_TX_Bit_Count[2]), .ZN
       (n_13));
  AOI22D1 g2702__5477(.A1 (n_11), .A2 (n_39), .B1 (n_44), .B2
       (r_RX_Bit_Count[2]), .ZN (n_12));
  NR2XD0 g2694__2398(.A1 (n_14), .A2 (r_SPI_Clk_Edges[3]), .ZN (n_16));
  OA21D1 g2695__5107(.A1 (n_7), .A2 (n_6), .B (n_14), .Z (n_10));
  SDFCNQD1 \r_TX_Byte_reg[5] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[5]), .SI (i_TX_Byte[5]), .SE (i_TX_DV), .Q
       (r_TX_Byte[5]));
  SDFCNQD1 \r_TX_Byte_reg[0] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[0]), .SI (i_TX_Byte[0]), .SE (i_TX_DV), .Q
       (r_TX_Byte[0]));
  SDFCNQD1 \r_TX_Byte_reg[3] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[3]), .SI (i_TX_Byte[3]), .SE (i_TX_DV), .Q
       (r_TX_Byte[3]));
  SDFCNQD1 \r_TX_Byte_reg[4] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[4]), .SI (i_TX_Byte[4]), .SE (i_TX_DV), .Q
       (r_TX_Byte[4]));
  SDFCNQD1 \r_TX_Byte_reg[6] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[6]), .SI (i_TX_Byte[6]), .SE (i_TX_DV), .Q
       (r_TX_Byte[6]));
  SDFCNQD1 \r_TX_Byte_reg[7] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[7]), .SI (i_TX_Byte[7]), .SE (i_TX_DV), .Q
       (r_TX_Byte[7]));
  AOI22D1 g2710__6260(.A1 (n_52), .A2 (r_TX_Byte[5]), .B1
       (r_TX_Byte[7]), .B2 (r_TX_Bit_Count[1]), .ZN (n_9));
  OAI22D1 g2711__4319(.A1 (r_TX_Byte[1]), .A2 (r_TX_Bit_Count[1]), .B1
       (n_52), .B2 (r_TX_Byte[3]), .ZN (n_8));
  SDFCNQD1 \r_TX_Byte_reg[2] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[2]), .SI (i_TX_Byte[2]), .SE (i_TX_DV), .Q
       (r_TX_Byte[2]));
  SDFCNQD1 \r_TX_Byte_reg[1] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[1]), .SI (i_TX_Byte[1]), .SE (i_TX_DV), .Q
       (r_TX_Byte[1]));
  CKND1 g2715(.I (n_44), .ZN (n_11));
  CKND2D1 g2696__8428(.A1 (n_7), .A2 (n_6), .ZN (n_14));
  MOAI22D1 g2707__5526(.A1 (r_SPI_Clk_Edges[1]), .A2
       (r_SPI_Clk_Edges[0]), .B1 (r_SPI_Clk_Edges[1]), .B2
       (r_SPI_Clk_Edges[0]), .ZN (n_5));
  MUX2ND0 g2708__6783(.I0 (r_TX_Byte[0]), .I1 (r_TX_Byte[4]), .S
       (r_TX_Bit_Count[2]), .ZN (n_4));
  CKND2D1 g2716__3680(.A1 (n_3), .A2 (r_RX_Bit_Count[1]), .ZN (n_66));
  MUX2D0 g2709__1617(.I0 (r_TX_Byte[2]), .I1 (r_TX_Byte[6]), .S
       (r_TX_Bit_Count[2]), .Z (n_2));
  CKND2D1 g2717__2802(.A1 (n_1), .A2 (r_RX_Bit_Count[0]), .ZN (n_64));
  ND2D1 g2719__1705(.A1 (n_1), .A2 (n_3), .ZN (n_44));
  NR2XD0 g2713__5122(.A1 (r_SPI_Clk_Edges[1]), .A2
       (r_SPI_Clk_Edges[0]), .ZN (n_7));
  ND2D1 g2718__8246(.A1 (r_RX_Bit_Count[0]), .A2 (r_RX_Bit_Count[1]),
       .ZN (n_70));
  DFCNQD1 o_SPI_Clk_reg(.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_SPI_Clk_Count[1]), .Q (o_SPI_Clk));
  DFCNQD1 r_TX_DV_reg(.CDN (i_Rst_L), .CP (i_Clk), .D (i_TX_DV), .Q
       (r_TX_DV));
  INR2D1 g2(.A1 (r_SPI_Clk_Edges[4]), .B1 (n_16), .ZN (n_95));
  DFCND1 r_Trailing_Edge_reg(.CDN (i_Rst_L), .CP (i_Clk), .D (n_24), .Q
       (r_Trailing_Edge), .QN (n_37));
  DFCND1 r_Leading_Edge_reg(.CDN (i_Rst_L), .CP (i_Clk), .D (n_20), .Q
       (r_Leading_Edge), .QN (n_41));
  DFCND1 o_TX_Ready_reg(.CDN (i_Rst_L), .CP (i_Clk), .D (n_18), .Q
       (o_TX_Ready), .QN (n_46));
  DFSND1 \r_RX_Bit_Count_reg[1] (.SDN (i_Rst_L), .CP (i_Clk), .D
       (n_47), .Q (r_RX_Bit_Count[1]), .QN (n_1));
  DFSND1 \r_RX_Bit_Count_reg[2] (.SDN (i_Rst_L), .CP (i_Clk), .D
       (n_43), .Q (r_RX_Bit_Count[2]), .QN (n_39));
  DFSND1 \r_TX_Bit_Count_reg[1] (.SDN (i_Rst_L), .CP (i_Clk), .D
       (n_72), .Q (r_TX_Bit_Count[1]), .QN (n_52));
  DFCND1 o_SPI_MOSI_reg(.CDN (i_Rst_L), .CP (i_Clk), .D (n_82), .Q
       (o_SPI_MOSI), .QN (n_0));
  DFCND1 \r_SPI_Clk_Edges_reg[2] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (n_32), .Q (r_SPI_Clk_Edges[2]), .QN (n_6));
  DFSND1 \r_RX_Bit_Count_reg[0] (.SDN (i_Rst_L), .CP (i_Clk), .D
       (n_42), .Q (r_RX_Bit_Count[0]), .QN (n_3));
endmodule

