
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point ext_spi_clkx2 ext_spi_clkx2 -type PI PI
add mapped point start_trans start_trans -type PI PI
add mapped point MISO MISO -type PI PI
add mapped point tx_data[31] tx_data[31] -type PI PI
add mapped point tx_data[30] tx_data[30] -type PI PI
add mapped point tx_data[29] tx_data[29] -type PI PI
add mapped point tx_data[28] tx_data[28] -type PI PI
add mapped point tx_data[27] tx_data[27] -type PI PI
add mapped point tx_data[26] tx_data[26] -type PI PI
add mapped point tx_data[25] tx_data[25] -type PI PI
add mapped point tx_data[24] tx_data[24] -type PI PI
add mapped point tx_data[23] tx_data[23] -type PI PI
add mapped point tx_data[22] tx_data[22] -type PI PI
add mapped point tx_data[21] tx_data[21] -type PI PI
add mapped point tx_data[20] tx_data[20] -type PI PI
add mapped point tx_data[19] tx_data[19] -type PI PI
add mapped point tx_data[18] tx_data[18] -type PI PI
add mapped point tx_data[17] tx_data[17] -type PI PI
add mapped point tx_data[16] tx_data[16] -type PI PI
add mapped point tx_data[15] tx_data[15] -type PI PI
add mapped point tx_data[14] tx_data[14] -type PI PI
add mapped point tx_data[13] tx_data[13] -type PI PI
add mapped point tx_data[12] tx_data[12] -type PI PI
add mapped point tx_data[11] tx_data[11] -type PI PI
add mapped point tx_data[10] tx_data[10] -type PI PI
add mapped point tx_data[9] tx_data[9] -type PI PI
add mapped point tx_data[8] tx_data[8] -type PI PI
add mapped point tx_data[7] tx_data[7] -type PI PI
add mapped point tx_data[6] tx_data[6] -type PI PI
add mapped point tx_data[5] tx_data[5] -type PI PI
add mapped point tx_data[4] tx_data[4] -type PI PI
add mapped point tx_data[3] tx_data[3] -type PI PI
add mapped point tx_data[2] tx_data[2] -type PI PI
add mapped point tx_data[1] tx_data[1] -type PI PI
add mapped point tx_data[0] tx_data[0] -type PI PI
add mapped point chipADDRS[2] chipADDRS[2] -type PI PI
add mapped point chipADDRS[1] chipADDRS[1] -type PI PI
add mapped point chipADDRS[0] chipADDRS[0] -type PI PI
add mapped point transaction_length[1] transaction_length[1] -type PI PI
add mapped point transaction_length[0] transaction_length[0] -type PI PI
add mapped point CPOL CPOL -type PI PI
add mapped point CPHA CPHA -type PI PI
add mapped point default_val default_val -type PI PI

//output ports
add mapped point busy busy -type PO PO
add mapped point MOSI MOSI -type PO PO
add mapped point SCLK SCLK -type PO PO
add mapped point CS[7] CS[7] -type PO PO
add mapped point CS[6] CS[6] -type PO PO
add mapped point CS[5] CS[5] -type PO PO
add mapped point CS[4] CS[4] -type PO PO
add mapped point CS[3] CS[3] -type PO PO
add mapped point CS[2] CS[2] -type PO PO
add mapped point CS[1] CS[1] -type PO PO
add mapped point CS[0] CS[0] -type PO PO
add mapped point rx_data[31] rx_data[31] -type PO PO
add mapped point rx_data[30] rx_data[30] -type PO PO
add mapped point rx_data[29] rx_data[29] -type PO PO
add mapped point rx_data[28] rx_data[28] -type PO PO
add mapped point rx_data[27] rx_data[27] -type PO PO
add mapped point rx_data[26] rx_data[26] -type PO PO
add mapped point rx_data[25] rx_data[25] -type PO PO
add mapped point rx_data[24] rx_data[24] -type PO PO
add mapped point rx_data[23] rx_data[23] -type PO PO
add mapped point rx_data[22] rx_data[22] -type PO PO
add mapped point rx_data[21] rx_data[21] -type PO PO
add mapped point rx_data[20] rx_data[20] -type PO PO
add mapped point rx_data[19] rx_data[19] -type PO PO
add mapped point rx_data[18] rx_data[18] -type PO PO
add mapped point rx_data[17] rx_data[17] -type PO PO
add mapped point rx_data[16] rx_data[16] -type PO PO
add mapped point rx_data[15] rx_data[15] -type PO PO
add mapped point rx_data[14] rx_data[14] -type PO PO
add mapped point rx_data[13] rx_data[13] -type PO PO
add mapped point rx_data[12] rx_data[12] -type PO PO
add mapped point rx_data[11] rx_data[11] -type PO PO
add mapped point rx_data[10] rx_data[10] -type PO PO
add mapped point rx_data[9] rx_data[9] -type PO PO
add mapped point rx_data[8] rx_data[8] -type PO PO
add mapped point rx_data[7] rx_data[7] -type PO PO
add mapped point rx_data[6] rx_data[6] -type PO PO
add mapped point rx_data[5] rx_data[5] -type PO PO
add mapped point rx_data[4] rx_data[4] -type PO PO
add mapped point rx_data[3] rx_data[3] -type PO PO
add mapped point rx_data[2] rx_data[2] -type PO PO
add mapped point rx_data[1] rx_data[1] -type PO PO
add mapped point rx_data[0] rx_data[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point rx_data[31]/q rx_data_reg[31]/Q -type DFF DFF
add mapped point rx_data[30]/q rx_data_reg[30]/Q -type DFF DFF
add mapped point tx_buff[32]/q tx_buff_reg[32]/Q -type DFF DFF
add mapped point rx_data[29]/q rx_data_reg[29]/Q -type DFF DFF
add mapped point rx_buff[31]/q rx_buff_reg[31]/Q -type DFF DFF
add mapped point tx_buff[31]/q tx_buff_reg[31]/Q -type DFF DFF
add mapped point rx_data[28]/q rx_data_reg[28]/Q -type DFF DFF
add mapped point rx_buff[30]/q rx_buff_reg[30]/Q -type DFF DFF
add mapped point tx_buff[30]/q tx_buff_reg[30]/Q -type DFF DFF
add mapped point rx_data[27]/q rx_data_reg[27]/Q -type DFF DFF
add mapped point rx_buff[29]/q rx_buff_reg[29]/Q -type DFF DFF
add mapped point tx_buff[29]/q tx_buff_reg[29]/Q -type DFF DFF
add mapped point rx_data[26]/q rx_data_reg[26]/Q -type DFF DFF
add mapped point rx_buff[28]/q rx_buff_reg[28]/Q -type DFF DFF
add mapped point tx_buff[28]/q tx_buff_reg[28]/Q -type DFF DFF
add mapped point rx_data[25]/q rx_data_reg[25]/Q -type DFF DFF
add mapped point rx_buff[27]/q rx_buff_reg[27]/Q -type DFF DFF
add mapped point tx_buff[27]/q tx_buff_reg[27]/Q -type DFF DFF
add mapped point rx_data[24]/q rx_data_reg[24]/Q -type DFF DFF
add mapped point rx_buff[26]/q rx_buff_reg[26]/Q -type DFF DFF
add mapped point tx_buff[26]/q tx_buff_reg[26]/Q -type DFF DFF
add mapped point rx_data[23]/q rx_data_reg[23]/Q -type DFF DFF
add mapped point rx_buff[25]/q rx_buff_reg[25]/Q -type DFF DFF
add mapped point tx_buff[25]/q tx_buff_reg[25]/Q -type DFF DFF
add mapped point rx_data[22]/q rx_data_reg[22]/Q -type DFF DFF
add mapped point rx_buff[24]/q rx_buff_reg[24]/Q -type DFF DFF
add mapped point tx_buff[24]/q tx_buff_reg[24]/Q -type DFF DFF
add mapped point rx_data[21]/q rx_data_reg[21]/Q -type DFF DFF
add mapped point rx_buff[23]/q rx_buff_reg[23]/Q -type DFF DFF
add mapped point tx_buff[23]/q tx_buff_reg[23]/Q -type DFF DFF
add mapped point rx_data[20]/q rx_data_reg[20]/Q -type DFF DFF
add mapped point rx_buff[22]/q rx_buff_reg[22]/Q -type DFF DFF
add mapped point tx_buff[22]/q tx_buff_reg[22]/Q -type DFF DFF
add mapped point rx_data[19]/q rx_data_reg[19]/Q -type DFF DFF
add mapped point rx_buff[21]/q rx_buff_reg[21]/Q -type DFF DFF
add mapped point tx_buff[21]/q tx_buff_reg[21]/Q -type DFF DFF
add mapped point rx_buff[20]/q rx_buff_reg[20]/Q -type DFF DFF
add mapped point rx_data[18]/q rx_data_reg[18]/Q -type DFF DFF
add mapped point tx_buff[20]/q tx_buff_reg[20]/Q -type DFF DFF
add mapped point rx_data[17]/q rx_data_reg[17]/Q -type DFF DFF
add mapped point rx_buff[19]/q rx_buff_reg[19]/Q -type DFF DFF
add mapped point tx_buff[19]/q tx_buff_reg[19]/Q -type DFF DFF
add mapped point rx_data[16]/q rx_data_reg[16]/Q -type DFF DFF
add mapped point rx_buff[18]/q rx_buff_reg[18]/Q -type DFF DFF
add mapped point tx_buff[18]/q tx_buff_reg[18]/Q -type DFF DFF
add mapped point rx_data[15]/q rx_data_reg[15]/Q -type DFF DFF
add mapped point rx_buff[17]/q rx_buff_reg[17]/Q -type DFF DFF
add mapped point tx_buff[17]/q tx_buff_reg[17]/Q -type DFF DFF
add mapped point rx_data[14]/q rx_data_reg[14]/Q -type DFF DFF
add mapped point rx_buff[16]/q rx_buff_reg[16]/Q -type DFF DFF
add mapped point tx_buff[16]/q tx_buff_reg[16]/Q -type DFF DFF
add mapped point rx_data[13]/q rx_data_reg[13]/Q -type DFF DFF
add mapped point rx_buff[15]/q rx_buff_reg[15]/Q -type DFF DFF
add mapped point tx_buff[15]/q tx_buff_reg[15]/Q -type DFF DFF
add mapped point rx_data[12]/q rx_data_reg[12]/Q -type DFF DFF
add mapped point rx_buff[14]/q rx_buff_reg[14]/Q -type DFF DFF
add mapped point tx_buff[14]/q tx_buff_reg[14]/Q -type DFF DFF
add mapped point rx_data[11]/q rx_data_reg[11]/Q -type DFF DFF
add mapped point rx_buff[13]/q rx_buff_reg[13]/Q -type DFF DFF
add mapped point tx_buff[13]/q tx_buff_reg[13]/Q -type DFF DFF
add mapped point rx_data[10]/q rx_data_reg[10]/Q -type DFF DFF
add mapped point rx_buff[12]/q rx_buff_reg[12]/Q -type DFF DFF
add mapped point tx_buff[12]/q tx_buff_reg[12]/Q -type DFF DFF
add mapped point rx_data[9]/q rx_data_reg[9]/Q -type DFF DFF
add mapped point rx_buff[11]/q rx_buff_reg[11]/Q -type DFF DFF
add mapped point tx_buff[11]/q tx_buff_reg[11]/Q -type DFF DFF
add mapped point rx_data[8]/q rx_data_reg[8]/Q -type DFF DFF
add mapped point rx_buff[10]/q rx_buff_reg[10]/Q -type DFF DFF
add mapped point tx_buff[10]/q tx_buff_reg[10]/Q -type DFF DFF
add mapped point rx_data[7]/q rx_data_reg[7]/Q -type DFF DFF
add mapped point rx_buff[9]/q rx_buff_reg[9]/Q -type DFF DFF
add mapped point tx_buff[9]/q tx_buff_reg[9]/Q -type DFF DFF
add mapped point rx_data[6]/q rx_data_reg[6]/Q -type DFF DFF
add mapped point rx_buff[8]/q rx_buff_reg[8]/Q -type DFF DFF
add mapped point tx_buff[8]/q tx_buff_reg[8]/Q -type DFF DFF
add mapped point rx_buff[7]/q rx_buff_reg[7]/Q -type DFF DFF
add mapped point rx_data[5]/q rx_data_reg[5]/Q -type DFF DFF
add mapped point tx_buff[7]/q tx_buff_reg[7]/Q -type DFF DFF
add mapped point rx_buff[6]/q rx_buff_reg[6]/Q -type DFF DFF
add mapped point rx_data[4]/q rx_data_reg[4]/Q -type DFF DFF
add mapped point tx_buff[6]/q tx_buff_reg[6]/Q -type DFF DFF
add mapped point rx_buff[5]/q rx_buff_reg[5]/Q -type DFF DFF
add mapped point rx_data[3]/q rx_data_reg[3]/Q -type DFF DFF
add mapped point tx_buff[5]/q tx_buff_reg[5]/Q -type DFF DFF
add mapped point rx_data[2]/q rx_data_reg[2]/Q -type DFF DFF
add mapped point rx_buff[4]/q rx_buff_reg[4]/Q -type DFF DFF
add mapped point tx_buff[4]/q tx_buff_reg[4]/Q -type DFF DFF
add mapped point SPI_transaction_counter[4]/q SPI_transaction_counter_reg[4]/Q -type DFF DFF
add mapped point rx_data[1]/q rx_data_reg[1]/Q -type DFF DFF
add mapped point rx_buff[3]/q rx_buff_reg[3]/Q -type DFF DFF
add mapped point SPI_transaction_counter[3]/q SPI_transaction_counter_reg[3]/Q -type DFF DFF
add mapped point tx_buff[3]/q tx_buff_reg[3]/Q -type DFF DFF
add mapped point rx_data[0]/q rx_data_reg[0]/Q -type DFF DFF
add mapped point SPI_transaction_counter[2]/q SPI_transaction_counter_reg[2]/Q -type DFF DFF
add mapped point rx_buff[2]/q rx_buff_reg[2]/Q -type DFF DFF
add mapped point tx_buff[2]/q tx_buff_reg[2]/Q -type DFF DFF
add mapped point SPI_state[0]/q SPI_state_reg[0]/Q -type DFF DFF
add mapped point CS[5]/q CS_reg[5]/Q -type DFF DFF
add mapped point rx_buff[1]/q rx_buff_reg[1]/Q -type DFF DFF
add mapped point SPI_transaction_counter[1]/q SPI_transaction_counter_reg[1]/Q -type DFF DFF
add mapped point CS[1]/q CS_reg[1]/Q -type DFF DFF
add mapped point CS[0]/q CS_reg[0]/Q -type DFF DFF
add mapped point CS[2]/q CS_reg[2]/Q -type DFF DFF
add mapped point CS[4]/q CS_reg[4]/Q -type DFF DFF
add mapped point tx_buff[1]/q tx_buff_reg[1]/Q -type DFF DFF
add mapped point CS[3]/q CS_reg[3]/Q -type DFF DFF
add mapped point CS[7]/q CS_reg[7]/Q -type DFF DFF
add mapped point CS[6]/q CS_reg[6]/Q -type DFF DFF
add mapped point rx_buff[0]/q rx_buff_reg[0]/Q -type DFF DFF
add mapped point SPI_transaction_counter[0]/q SPI_transaction_counter_reg[0]/Q -type DFF DFF
add mapped point tx_buff[0]/q tx_buff_reg[0]/Q -type DFF DFF
add mapped point SPI_state[1]/q SPI_state_reg[1]/Q -type DFF DFF
add mapped point spi_clk_main/q spi_clk_main_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
