
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May 23 2026 02:47:21 IST (May 22 2026 21:17:21 UTC)

// Verification Directory fv/spi_master 

module spi_master(clk, rst, ext_spi_clkx2, start_trans, busy, MOSI,
     MISO, SCLK, CS, tx_data, rx_data, chipADDRS, transaction_length,
     CPOL, CPHA, default_val);
  input clk, rst, ext_spi_clkx2, start_trans, MISO, CPOL, CPHA,
       default_val;
  input [31:0] tx_data;
  input [2:0] chipADDRS;
  input [1:0] transaction_length;
  output busy, MOSI, SCLK;
  output [7:0] CS;
  output [31:0] rx_data;
  wire clk, rst, ext_spi_clkx2, start_trans, MISO, CPOL, CPHA,
       default_val;
  wire [31:0] tx_data;
  wire [2:0] chipADDRS;
  wire [1:0] transaction_length;
  wire busy, MOSI, SCLK;
  wire [7:0] CS;
  wire [31:0] rx_data;
  wire [32:0] tx_buff;
  wire [31:0] rx_buff;
  wire [4:0] SPI_transaction_counter;
  wire [1:0] SPI_state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_95, n_96, n_97, n_98, n_100, n_101, n_102;
  wire n_103, n_104, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_193, n_194, spi_clk_main;
  OAI31D0 g4377__2398(.A1 (n_145), .A2 (n_134), .A3 (n_140), .B
       (n_146), .ZN (MOSI));
  AOI221D0 g4378__5107(.A1 (n_143), .A2 (default_val), .B1 (n_135), .B2
       (n_145), .C (n_144), .ZN (n_146));
  NR3D0 g4379__6260(.A1 (n_143), .A2 (n_142), .A3 (n_145), .ZN (n_144));
  OAI221D0 g4380__4319(.A1 (tx_buff[32]), .A2 (n_139), .B1
       (transaction_length[1]), .B2 (tx_buff[16]), .C (CPHA), .ZN
       (n_142));
  SDFQD0 \rx_data_reg[31] (.CP (clk), .D (rx_buff[31]), .SI
       (rx_data[31]), .SE (n_141), .Q (rx_data[31]));
  SDFQD0 \rx_data_reg[30] (.CP (clk), .D (rx_buff[30]), .SI
       (rx_data[30]), .SE (n_141), .Q (rx_data[30]));
  AOI22D0 g4383__8428(.A1 (tx_buff[31]), .A2 (transaction_length[1]),
       .B1 (tx_buff[15]), .B2 (n_139), .ZN (n_140));
  DFCSNQD1 \tx_buff_reg[32] (.CDN (n_64), .SDN (n_42), .CP (n_137), .D
       (tx_buff[31]), .Q (tx_buff[32]));
  SDFQD0 \rx_data_reg[29] (.CP (clk), .D (rx_buff[29]), .SI
       (rx_data[29]), .SE (n_141), .Q (rx_data[29]));
  DFCNQD1 \rx_buff_reg[31] (.CDN (busy), .CP (n_136), .D (rx_buff[30]),
       .Q (rx_buff[31]));
  DFCSNQD1 \tx_buff_reg[31] (.CDN (n_83), .SDN (n_43), .CP (n_137), .D
       (tx_buff[30]), .Q (tx_buff[31]));
  SDFQD0 \rx_data_reg[28] (.CP (clk), .D (rx_buff[28]), .SI
       (rx_data[28]), .SE (n_141), .Q (rx_data[28]));
  DFCNQD1 \rx_buff_reg[30] (.CDN (busy), .CP (n_136), .D (rx_buff[29]),
       .Q (rx_buff[30]));
  DFCSNQD1 \tx_buff_reg[30] (.CDN (n_60), .SDN (n_28), .CP (n_137), .D
       (tx_buff[29]), .Q (tx_buff[30]));
  SDFQD0 \rx_data_reg[27] (.CP (clk), .D (rx_buff[27]), .SI
       (rx_data[27]), .SE (n_141), .Q (rx_data[27]));
  DFCNQD1 \rx_buff_reg[29] (.CDN (busy), .CP (n_136), .D (rx_buff[28]),
       .Q (rx_buff[29]));
  DFCSNQD1 \tx_buff_reg[29] (.CDN (n_53), .SDN (n_29), .CP (n_137), .D
       (tx_buff[28]), .Q (tx_buff[29]));
  SDFQD0 \rx_data_reg[26] (.CP (clk), .D (rx_buff[26]), .SI
       (rx_data[26]), .SE (n_141), .Q (rx_data[26]));
  OAI31D0 g4391__5526(.A1 (transaction_length[1]), .A2 (n_134), .A3
       (n_131), .B (n_133), .ZN (n_135));
  DFCNQD1 \rx_buff_reg[28] (.CDN (busy), .CP (n_136), .D (rx_buff[27]),
       .Q (rx_buff[28]));
  DFCSNQD1 \tx_buff_reg[28] (.CDN (n_82), .SDN (n_38), .CP (n_137), .D
       (tx_buff[27]), .Q (tx_buff[28]));
  AOI33D0 g4395__6783(.A1 (busy), .A2 (n_132), .A3 (CPHA), .B1
       (tx_buff[23]), .B2 (transaction_length[1]), .B3 (n_9), .ZN
       (n_133));
  SDFQD0 \rx_data_reg[25] (.CP (clk), .D (rx_buff[25]), .SI
       (rx_data[25]), .SE (n_141), .Q (rx_data[25]));
  DFCNQD1 \rx_buff_reg[27] (.CDN (busy), .CP (n_136), .D (rx_buff[26]),
       .Q (rx_buff[27]));
  DFCSNQD1 \tx_buff_reg[27] (.CDN (n_54), .SDN (n_46), .CP (n_137), .D
       (tx_buff[26]), .Q (tx_buff[27]));
  SDFQD0 \rx_data_reg[24] (.CP (clk), .D (rx_buff[24]), .SI
       (rx_data[24]), .SE (n_141), .Q (rx_data[24]));
  DFCNQD1 \rx_buff_reg[26] (.CDN (busy), .CP (n_136), .D (rx_buff[25]),
       .Q (rx_buff[26]));
  DFCSNQD1 \tx_buff_reg[26] (.CDN (n_79), .SDN (n_40), .CP (n_137), .D
       (tx_buff[25]), .Q (tx_buff[26]));
  SDFQD0 \rx_data_reg[23] (.CP (clk), .D (rx_buff[23]), .SI
       (rx_data[23]), .SE (n_141), .Q (rx_data[23]));
  AO22D0 g4405__3680(.A1 (tx_buff[24]), .A2 (transaction_length[1]),
       .B1 (n_139), .B2 (tx_buff[8]), .Z (n_132));
  DFCNQD1 \rx_buff_reg[25] (.CDN (busy), .CP (n_136), .D (rx_buff[24]),
       .Q (rx_buff[25]));
  DFCSNQD1 \tx_buff_reg[25] (.CDN (n_56), .SDN (n_44), .CP (n_137), .D
       (tx_buff[24]), .Q (tx_buff[25]));
  SDFQD0 \rx_data_reg[22] (.CP (clk), .D (rx_buff[22]), .SI
       (rx_data[22]), .SE (n_141), .Q (rx_data[22]));
  DFCNQD1 \rx_buff_reg[24] (.CDN (busy), .CP (n_136), .D (rx_buff[23]),
       .Q (rx_buff[24]));
  DFCSNQD1 \tx_buff_reg[24] (.CDN (n_57), .SDN (n_37), .CP (n_137), .D
       (tx_buff[23]), .Q (tx_buff[24]));
  SDFQD0 \rx_data_reg[21] (.CP (clk), .D (rx_buff[21]), .SI
       (rx_data[21]), .SE (n_141), .Q (rx_data[21]));
  DFCNQD1 \rx_buff_reg[23] (.CDN (busy), .CP (n_136), .D (rx_buff[22]),
       .Q (rx_buff[23]));
  DFCSNQD1 \tx_buff_reg[23] (.CDN (n_59), .SDN (n_15), .CP (n_137), .D
       (tx_buff[22]), .Q (tx_buff[23]));
  DFCNQD1 \rx_buff_reg[22] (.CDN (busy), .CP (n_136), .D (rx_buff[21]),
       .Q (rx_buff[22]));
  SDFQD0 \rx_data_reg[20] (.CP (clk), .D (rx_buff[20]), .SI
       (rx_data[20]), .SE (n_141), .Q (rx_data[20]));
  DFCSNQD1 \tx_buff_reg[22] (.CDN (n_55), .SDN (n_12), .CP (n_137), .D
       (tx_buff[21]), .Q (tx_buff[22]));
  DFCNQD1 \rx_buff_reg[21] (.CDN (busy), .CP (n_136), .D (rx_buff[20]),
       .Q (rx_buff[21]));
  SDFQD0 \rx_data_reg[19] (.CP (clk), .D (rx_buff[19]), .SI
       (rx_data[19]), .SE (n_141), .Q (rx_data[19]));
  DFCSNQD1 \tx_buff_reg[21] (.CDN (n_66), .SDN (n_32), .CP (n_137), .D
       (tx_buff[20]), .Q (tx_buff[21]));
  SDFQD0 \rx_data_reg[18] (.CP (clk), .D (rx_buff[18]), .SI
       (rx_data[18]), .SE (n_141), .Q (rx_data[18]));
  DFCNQD1 \rx_buff_reg[20] (.CDN (busy), .CP (n_136), .D (rx_buff[19]),
       .Q (rx_buff[20]));
  DFCSNQD1 \tx_buff_reg[20] (.CDN (n_84), .SDN (n_51), .CP (n_137), .D
       (tx_buff[19]), .Q (tx_buff[20]));
  SDFQD0 \rx_data_reg[17] (.CP (clk), .D (rx_buff[17]), .SI
       (rx_data[17]), .SE (n_141), .Q (rx_data[17]));
  DFCNQD1 \rx_buff_reg[19] (.CDN (busy), .CP (n_136), .D (rx_buff[18]),
       .Q (rx_buff[19]));
  DFCSNQD1 \tx_buff_reg[19] (.CDN (n_73), .SDN (n_25), .CP (n_137), .D
       (tx_buff[18]), .Q (tx_buff[19]));
  SDFQD0 \rx_data_reg[16] (.CP (clk), .D (rx_buff[16]), .SI
       (rx_data[16]), .SE (n_141), .Q (rx_data[16]));
  DFCNQD1 \rx_buff_reg[18] (.CDN (busy), .CP (n_136), .D (rx_buff[17]),
       .Q (rx_buff[18]));
  DFCSNQD1 \tx_buff_reg[18] (.CDN (n_61), .SDN (n_27), .CP (n_137), .D
       (tx_buff[17]), .Q (tx_buff[18]));
  SDFQD0 \rx_data_reg[15] (.CP (clk), .D (rx_buff[15]), .SI
       (rx_data[15]), .SE (n_141), .Q (rx_data[15]));
  DFCNQD1 \rx_buff_reg[17] (.CDN (busy), .CP (n_136), .D (rx_buff[16]),
       .Q (rx_buff[17]));
  DFCSNQD1 \tx_buff_reg[17] (.CDN (n_78), .SDN (n_33), .CP (n_137), .D
       (tx_buff[16]), .Q (tx_buff[17]));
  SDFQD0 \rx_data_reg[14] (.CP (clk), .D (rx_buff[14]), .SI
       (rx_data[14]), .SE (n_141), .Q (rx_data[14]));
  DFCNQD1 \rx_buff_reg[16] (.CDN (busy), .CP (n_136), .D (rx_buff[15]),
       .Q (rx_buff[16]));
  DFCSNQD1 \tx_buff_reg[16] (.CDN (n_62), .SDN (n_41), .CP (n_137), .D
       (tx_buff[15]), .Q (tx_buff[16]));
  SDFQD0 \rx_data_reg[13] (.CP (clk), .D (rx_buff[13]), .SI
       (rx_data[13]), .SE (n_141), .Q (rx_data[13]));
  DFCNQD1 \rx_buff_reg[15] (.CDN (busy), .CP (n_136), .D (rx_buff[14]),
       .Q (rx_buff[15]));
  DFCSNQD1 \tx_buff_reg[15] (.CDN (n_63), .SDN (n_31), .CP (n_137), .D
       (tx_buff[14]), .Q (tx_buff[15]));
  SDFQD0 \rx_data_reg[12] (.CP (clk), .D (rx_buff[12]), .SI
       (rx_data[12]), .SE (n_141), .Q (rx_data[12]));
  DFCNQD1 \rx_buff_reg[14] (.CDN (busy), .CP (n_136), .D (rx_buff[13]),
       .Q (rx_buff[14]));
  DFCSNQD1 \tx_buff_reg[14] (.CDN (n_77), .SDN (n_16), .CP (n_137), .D
       (tx_buff[13]), .Q (tx_buff[14]));
  SDFQD0 \rx_data_reg[11] (.CP (clk), .D (rx_buff[11]), .SI
       (rx_data[11]), .SE (n_141), .Q (rx_data[11]));
  DFCNQD1 \rx_buff_reg[13] (.CDN (busy), .CP (n_136), .D (rx_buff[12]),
       .Q (rx_buff[13]));
  DFCSNQD1 \tx_buff_reg[13] (.CDN (n_65), .SDN (n_47), .CP (n_137), .D
       (tx_buff[12]), .Q (tx_buff[13]));
  SDFQD0 \rx_data_reg[10] (.CP (clk), .D (rx_buff[10]), .SI
       (rx_data[10]), .SE (n_141), .Q (rx_data[10]));
  DFCNQD1 \rx_buff_reg[12] (.CDN (busy), .CP (n_136), .D (rx_buff[11]),
       .Q (rx_buff[12]));
  DFCSNQD1 \tx_buff_reg[12] (.CDN (n_74), .SDN (n_17), .CP (n_137), .D
       (tx_buff[11]), .Q (tx_buff[12]));
  SDFQD0 \rx_data_reg[9] (.CP (clk), .D (rx_buff[9]), .SI (rx_data[9]),
       .SE (n_141), .Q (rx_data[9]));
  DFCNQD1 \rx_buff_reg[11] (.CDN (busy), .CP (n_136), .D (rx_buff[10]),
       .Q (rx_buff[11]));
  DFCSNQD1 \tx_buff_reg[11] (.CDN (n_76), .SDN (n_45), .CP (n_137), .D
       (tx_buff[10]), .Q (tx_buff[11]));
  SDFQD0 \rx_data_reg[8] (.CP (clk), .D (rx_buff[8]), .SI (rx_data[8]),
       .SE (n_141), .Q (rx_data[8]));
  DFCNQD1 \rx_buff_reg[10] (.CDN (busy), .CP (n_136), .D (rx_buff[9]),
       .Q (rx_buff[10]));
  DFCSNQD1 \tx_buff_reg[10] (.CDN (n_75), .SDN (n_19), .CP (n_137), .D
       (tx_buff[9]), .Q (tx_buff[10]));
  SDFQD0 \rx_data_reg[7] (.CP (clk), .D (rx_buff[7]), .SI (rx_data[7]),
       .SE (n_141), .Q (rx_data[7]));
  DFCNQD1 \rx_buff_reg[9] (.CDN (busy), .CP (n_136), .D (rx_buff[8]),
       .Q (rx_buff[9]));
  DFCSNQD1 \tx_buff_reg[9] (.CDN (n_67), .SDN (n_34), .CP (n_137), .D
       (tx_buff[8]), .Q (tx_buff[9]));
  SDFQD0 \rx_data_reg[6] (.CP (clk), .D (rx_buff[6]), .SI (rx_data[6]),
       .SE (n_141), .Q (rx_data[6]));
  DFCNQD1 \rx_buff_reg[8] (.CDN (busy), .CP (n_136), .D (rx_buff[7]),
       .Q (rx_buff[8]));
  DFCSNQD1 \tx_buff_reg[8] (.CDN (n_68), .SDN (n_50), .CP (n_137), .D
       (tx_buff[7]), .Q (tx_buff[8]));
  DFCNQD1 \rx_buff_reg[7] (.CDN (busy), .CP (n_136), .D (rx_buff[6]),
       .Q (rx_buff[7]));
  CKND0 g4465(.I (tx_buff[7]), .ZN (n_131));
  SDFQD0 \rx_data_reg[5] (.CP (clk), .D (rx_buff[5]), .SI (rx_data[5]),
       .SE (n_141), .Q (rx_data[5]));
  DFCSNQD1 \tx_buff_reg[7] (.CDN (n_69), .SDN (n_20), .CP (n_137), .D
       (tx_buff[6]), .Q (tx_buff[7]));
  DFCNQD1 \rx_buff_reg[6] (.CDN (busy), .CP (n_136), .D (rx_buff[5]),
       .Q (rx_buff[6]));
  SDFQD0 \rx_data_reg[4] (.CP (clk), .D (rx_buff[4]), .SI (rx_data[4]),
       .SE (n_141), .Q (rx_data[4]));
  DFCSNQD1 \tx_buff_reg[6] (.CDN (n_70), .SDN (n_36), .CP (n_137), .D
       (tx_buff[5]), .Q (tx_buff[6]));
  SDFQD0 \rx_data_reg[3] (.CP (clk), .D (rx_buff[3]), .SI (rx_data[3]),
       .SE (n_141), .Q (rx_data[3]));
  DFCNQD1 \rx_buff_reg[5] (.CDN (busy), .CP (n_136), .D (rx_buff[4]),
       .Q (rx_buff[5]));
  DFCSNQD1 \tx_buff_reg[5] (.CDN (n_85), .SDN (n_35), .CP (n_137), .D
       (tx_buff[4]), .Q (tx_buff[5]));
  DFCNQD1 \rx_buff_reg[4] (.CDN (busy), .CP (n_136), .D (rx_buff[3]),
       .Q (rx_buff[4]));
  SDFQD0 \rx_data_reg[2] (.CP (clk), .D (rx_buff[2]), .SI (rx_data[2]),
       .SE (n_141), .Q (rx_data[2]));
  DFNCSND1 \SPI_transaction_counter_reg[4] (.CDN (n_26), .SDN (n_30),
       .CPN (ext_spi_clkx2), .D (n_130), .Q
       (SPI_transaction_counter[4]), .QN (UNCONNECTED));
  DFCSNQD1 \tx_buff_reg[4] (.CDN (n_87), .SDN (n_39), .CP (n_137), .D
       (tx_buff[3]), .Q (tx_buff[4]));
  DFNCSND1 \SPI_transaction_counter_reg[3] (.CDN (n_11), .SDN (n_10),
       .CPN (ext_spi_clkx2), .D (n_128), .Q
       (SPI_transaction_counter[3]), .QN (UNCONNECTED0));
  SDFQD0 \rx_data_reg[1] (.CP (clk), .D (rx_buff[1]), .SI (rx_data[1]),
       .SE (n_141), .Q (rx_data[1]));
  DFCNQD1 \rx_buff_reg[3] (.CDN (busy), .CP (n_136), .D (rx_buff[2]),
       .Q (rx_buff[3]));
  DFQD1 \CS_reg[5] (.CP (clk), .D (n_126), .Q (CS[5]));
  DFQD1 \CS_reg[7] (.CP (clk), .D (n_127), .Q (CS[7]));
  DFCSNQD1 \tx_buff_reg[3] (.CDN (n_81), .SDN (n_21), .CP (n_137), .D
       (tx_buff[2]), .Q (tx_buff[3]));
  MOAI22D0 g4452__1617(.A1 (n_129), .A2 (SPI_transaction_counter[4]),
       .B1 (n_129), .B2 (SPI_transaction_counter[4]), .ZN (n_130));
  SDFQD0 \rx_data_reg[0] (.CP (clk), .D (rx_buff[0]), .SI (rx_data[0]),
       .SE (n_141), .Q (rx_data[0]));
  DFQD1 \CS_reg[3] (.CP (clk), .D (n_119), .Q (CS[3]));
  DFNCND1 \SPI_transaction_counter_reg[2] (.CDN (n_122), .CPN
       (ext_spi_clkx2), .D (n_124), .Q (SPI_transaction_counter[2]),
       .QN (UNCONNECTED1));
  OA21D0 g4463__2802(.A1 (n_123), .A2 (SPI_transaction_counter[3]), .B
       (n_129), .Z (n_128));
  DFCNQD1 \rx_buff_reg[2] (.CDN (busy), .CP (n_136), .D (rx_buff[1]),
       .Q (rx_buff[2]));
  DFQD1 \CS_reg[2] (.CP (clk), .D (n_121), .Q (CS[2]));
  DFQD1 \CS_reg[1] (.CP (clk), .D (n_120), .Q (CS[1]));
  DFCSNQD1 \tx_buff_reg[2] (.CDN (n_72), .SDN (n_18), .CP (n_137), .D
       (tx_buff[1]), .Q (tx_buff[2]));
  DFQD1 \CS_reg[6] (.CP (clk), .D (n_115), .Q (CS[6]));
  DFQD1 \CS_reg[0] (.CP (clk), .D (n_116), .Q (CS[0]));
  OAI211D1 g4510__1705(.A1 (start_trans), .A2 (n_110), .B (n_111), .C
       (n_125), .ZN (n_127));
  CKND2D1 g4511__5122(.A1 (n_114), .A2 (n_125), .ZN (n_126));
  DFQD1 \CS_reg[4] (.CP (clk), .D (n_117), .Q (CS[4]));
  IAO21D0 g4476__8246(.A1 (n_113), .A2 (SPI_transaction_counter[2]), .B
       (n_123), .ZN (n_124));
  DFNCND1 \SPI_transaction_counter_reg[1] (.CDN (n_122), .CPN
       (ext_spi_clkx2), .D (n_112), .Q (SPI_transaction_counter[1]),
       .QN (UNCONNECTED2));
  CKND2D0 g4470__7098(.A1 (n_123), .A2 (SPI_transaction_counter[3]),
       .ZN (n_129));
  OAI211D1 g4508__6131(.A1 (start_trans), .A2 (n_193), .B (n_106), .C
       (n_125), .ZN (n_121));
  OAI211D1 g4507__1881(.A1 (start_trans), .A2 (n_103), .B (n_104), .C
       (n_125), .ZN (n_120));
  OAI211D1 g4509__5115(.A1 (start_trans), .A2 (n_101), .B (n_102), .C
       (n_125), .ZN (n_119));
  DFCNQD1 \rx_buff_reg[1] (.CDN (busy), .CP (n_136), .D (rx_buff[0]),
       .Q (rx_buff[1]));
  OAI32D1 g4482__7482(.A1 (rst), .A2 (n_90), .A3 (n_22), .B1 (n_89),
       .B2 (n_23), .ZN (n_118));
  DFCSNQD1 \tx_buff_reg[1] (.CDN (n_71), .SDN (n_48), .CP (n_137), .D
       (tx_buff[0]), .Q (tx_buff[1]));
  CKND2D1 g4500__4733(.A1 (n_109), .A2 (n_125), .ZN (n_117));
  CKND2D1 g4501__6161(.A1 (n_107), .A2 (n_125), .ZN (n_116));
  OAI211D1 g4506__9315(.A1 (start_trans), .A2 (n_95), .B (n_96), .C
       (n_125), .ZN (n_115));
  MUX2ND0 g4515__9945(.I0 (CS[5]), .I1 (n_108), .S (n_100), .ZN
       (n_114));
  DFNCND1 \SPI_transaction_counter_reg[0] (.CDN (n_122), .CPN
       (ext_spi_clkx2), .D (n_97), .Q (SPI_transaction_counter[0]), .QN
       (UNCONNECTED3));
  CKAN2D1 g4484__2883(.A1 (n_113), .A2 (SPI_transaction_counter[2]), .Z
       (n_123));
  IAO21D0 g4493__2346(.A1 (n_98), .A2 (SPI_transaction_counter[1]), .B
       (n_113), .ZN (n_112));
  ND2D1 g4523__1666(.A1 (CS[7]), .A2 (n_110), .ZN (n_111));
  DFCNQD1 \rx_buff_reg[0] (.CDN (busy), .CP (n_136), .D (MISO), .Q
       (rx_buff[0]));
  DFCSNQD1 \tx_buff_reg[0] (.CDN (n_80), .SDN (n_24), .CP (n_137), .D
       (default_val), .Q (tx_buff[0]));
  MUX2ND0 g4514__7410(.I0 (CS[4]), .I1 (n_108), .S (n_86), .ZN (n_109));
  MUX2ND0 g4516__6417(.I0 (CS[0]), .I1 (n_108), .S (n_58), .ZN (n_107));
  ND2D1 g4517__5477(.A1 (CS[2]), .A2 (n_193), .ZN (n_106));
  ND2D1 g4518__2398(.A1 (CS[1]), .A2 (n_103), .ZN (n_104));
  ND2D1 g4519__5107(.A1 (CS[3]), .A2 (n_101), .ZN (n_102));
  NR2XD0 g4530__6260(.A1 (n_194), .A2 (chipADDRS[1]), .ZN (n_100));
  OR2D1 g4535__4319(.A1 (n_194), .A2 (n_91), .Z (n_110));
  CKAN2D1 g4503__8428(.A1 (n_98), .A2 (SPI_transaction_counter[1]), .Z
       (n_113));
  IAO21D0 g4522__5526(.A1 (n_93), .A2 (SPI_transaction_counter[0]), .B
       (n_98), .ZN (n_97));
  ND2D1 g4524__6783(.A1 (CS[6]), .A2 (n_95), .ZN (n_96));
  CKND0 g4521(.I (n_137), .ZN (n_136));
  MUX2ND0 g4525__3680(.I0 (n_88), .I1 (n_93), .S (CPOL), .ZN (SCLK));
  CKND2D1 g4528__2802(.A1 (n_92), .A2 (chipADDRS[1]), .ZN (n_101));
  CKND2D1 g4529__1705(.A1 (n_92), .A2 (n_91), .ZN (n_103));
  INR4D0 g4505__5122(.A1 (ext_spi_clkx2), .B1
       (SPI_transaction_counter[3]), .B2 (n_93), .B3 (n_3), .ZN (n_90));
  INVD1 g4579(.I (n_125), .ZN (n_89));
  MUX2ND0 g4526__8246(.I0 (n_93), .I1 (n_88), .S (CPHA), .ZN (n_137));
  OR2D0 g4554__7098(.A1 (n_122), .A2 (tx_data[4]), .Z (n_87));
  NR2XD0 g4527__6131(.A1 (n_52), .A2 (chipADDRS[1]), .ZN (n_86));
  OR2D0 g4586__1881(.A1 (n_122), .A2 (tx_data[5]), .Z (n_85));
  OR2D0 g4541__5115(.A1 (n_122), .A2 (tx_data[20]), .Z (n_84));
  OR2D0 g4543__7482(.A1 (n_122), .A2 (tx_data[31]), .Z (n_83));
  OR2D0 g4544__4733(.A1 (n_122), .A2 (tx_data[28]), .Z (n_82));
  OR2D0 g4546__6161(.A1 (n_122), .A2 (tx_data[3]), .Z (n_81));
  OR2D0 g4547__9315(.A1 (n_122), .A2 (tx_data[0]), .Z (n_80));
  OR2D0 g4549__9945(.A1 (n_122), .A2 (tx_data[26]), .Z (n_79));
  OR2D0 g4592__2883(.A1 (n_122), .A2 (tx_data[17]), .Z (n_78));
  OR2D0 g4555__2346(.A1 (n_122), .A2 (tx_data[14]), .Z (n_77));
  OR2D0 g4561__1666(.A1 (n_122), .A2 (tx_data[11]), .Z (n_76));
  OR2D0 g4563__7410(.A1 (n_122), .A2 (tx_data[10]), .Z (n_75));
  OR2D0 g4565__6417(.A1 (n_122), .A2 (tx_data[12]), .Z (n_74));
  OR2D0 g4572__5477(.A1 (n_122), .A2 (tx_data[19]), .Z (n_73));
  OR2D0 g4583__2398(.A1 (n_122), .A2 (tx_data[2]), .Z (n_72));
  OR2D0 g4582__5107(.A1 (n_122), .A2 (tx_data[1]), .Z (n_71));
  CKAN2D1 g4536__4319(.A1 (n_93), .A2 (SPI_transaction_counter[0]), .Z
       (n_98));
  OR2D0 g4587__8428(.A1 (n_122), .A2 (tx_data[6]), .Z (n_70));
  OR2D0 g4588__5526(.A1 (n_122), .A2 (tx_data[7]), .Z (n_69));
  OR2D0 g4590__6783(.A1 (n_122), .A2 (tx_data[8]), .Z (n_68));
  OR2D0 g4591__3680(.A1 (n_122), .A2 (tx_data[9]), .Z (n_67));
  OR2D0 g4593__1617(.A1 (n_122), .A2 (tx_data[21]), .Z (n_66));
  OR2D0 g4594__2802(.A1 (n_122), .A2 (tx_data[13]), .Z (n_65));
  OR2D0 g4610__1705(.A1 (n_122), .A2 (default_val), .Z (n_64));
  OR2D0 g4595__5122(.A1 (n_122), .A2 (tx_data[15]), .Z (n_63));
  OR2D0 g4596__8246(.A1 (n_122), .A2 (tx_data[16]), .Z (n_62));
  OR2D0 g4599__7098(.A1 (n_122), .A2 (tx_data[18]), .Z (n_61));
  OR2D0 g4600__6131(.A1 (n_122), .A2 (tx_data[30]), .Z (n_60));
  OR2D0 g4603__1881(.A1 (n_122), .A2 (tx_data[23]), .Z (n_59));
  NR2XD0 g4533__5115(.A1 (n_13), .A2 (chipADDRS[1]), .ZN (n_58));
  OR2D0 g4605__7482(.A1 (n_122), .A2 (tx_data[24]), .Z (n_57));
  OR2D0 g4606__4733(.A1 (n_122), .A2 (tx_data[25]), .Z (n_56));
  OR2D0 g4607__6161(.A1 (n_122), .A2 (tx_data[22]), .Z (n_55));
  OR2D0 g4608__9315(.A1 (n_122), .A2 (tx_data[27]), .Z (n_54));
  OR2D0 g4609__9945(.A1 (n_122), .A2 (tx_data[29]), .Z (n_53));
  IND2D1 g4531__2883(.A1 (n_52), .B1 (chipADDRS[1]), .ZN (n_95));
  NR2XD0 g4619__2346(.A1 (n_4), .A2 (rst), .ZN (n_125));
  CKND2D0 g4538__1666(.A1 (n_49), .A2 (tx_data[20]), .ZN (n_51));
  CKND2D0 g4539__7410(.A1 (n_49), .A2 (tx_data[8]), .ZN (n_50));
  CKND2D0 g4540__6417(.A1 (n_49), .A2 (tx_data[1]), .ZN (n_48));
  CKND2D0 g4542__5477(.A1 (n_49), .A2 (tx_data[13]), .ZN (n_47));
  CKND2D0 g4545__2398(.A1 (n_49), .A2 (tx_data[27]), .ZN (n_46));
  CKND2D0 g4548__5107(.A1 (n_49), .A2 (tx_data[11]), .ZN (n_45));
  CKND2D0 g4550__6260(.A1 (n_49), .A2 (tx_data[25]), .ZN (n_44));
  CKND2D0 g4551__4319(.A1 (n_49), .A2 (tx_data[31]), .ZN (n_43));
  CKND2D0 g4552__8428(.A1 (n_49), .A2 (default_val), .ZN (n_42));
  CKND2D0 g4553__5526(.A1 (n_49), .A2 (tx_data[16]), .ZN (n_41));
  CKND2D0 g4556__6783(.A1 (n_49), .A2 (tx_data[26]), .ZN (n_40));
  CKND2D0 g4557__3680(.A1 (n_49), .A2 (tx_data[4]), .ZN (n_39));
  CKND2D0 g4558__1617(.A1 (n_49), .A2 (tx_data[28]), .ZN (n_38));
  CKND2D0 g4559__2802(.A1 (n_49), .A2 (tx_data[24]), .ZN (n_37));
  CKND2D0 g4560__1705(.A1 (n_49), .A2 (tx_data[6]), .ZN (n_36));
  CKND2D0 g4562__5122(.A1 (n_49), .A2 (tx_data[5]), .ZN (n_35));
  CKND2D0 g4564__8246(.A1 (n_49), .A2 (tx_data[9]), .ZN (n_34));
  CKND2D0 g4566__7098(.A1 (n_49), .A2 (tx_data[17]), .ZN (n_33));
  CKND2D0 g4567__6131(.A1 (n_49), .A2 (tx_data[21]), .ZN (n_32));
  CKND2D0 g4568__1881(.A1 (n_49), .A2 (tx_data[15]), .ZN (n_31));
  CKND2D0 g4616__5115(.A1 (n_49), .A2 (n_139), .ZN (n_30));
  CKND2D0 g4570__7482(.A1 (n_49), .A2 (tx_data[29]), .ZN (n_29));
  CKND2D0 g4571__4733(.A1 (n_49), .A2 (tx_data[30]), .ZN (n_28));
  CKND2D0 g4569__6161(.A1 (n_49), .A2 (tx_data[18]), .ZN (n_27));
  CKND2D0 g4615__9315(.A1 (n_49), .A2 (transaction_length[1]), .ZN
       (n_26));
  CKND2D0 g4580__9945(.A1 (n_49), .A2 (tx_data[19]), .ZN (n_25));
  CKND2D0 g4581__2883(.A1 (n_49), .A2 (tx_data[0]), .ZN (n_24));
  AOI21D1 g4584__2346(.A1 (n_22), .A2 (start_trans), .B (n_49), .ZN
       (n_23));
  CKND2D0 g4585__1666(.A1 (n_49), .A2 (tx_data[3]), .ZN (n_21));
  CKND2D0 g4589__7410(.A1 (n_49), .A2 (tx_data[7]), .ZN (n_20));
  CKND2D0 g4597__6417(.A1 (n_49), .A2 (tx_data[10]), .ZN (n_19));
  CKND2D0 g4598__5477(.A1 (n_49), .A2 (tx_data[2]), .ZN (n_18));
  CKND2D0 g4601__2398(.A1 (n_49), .A2 (tx_data[12]), .ZN (n_17));
  CKND2D0 g4602__5107(.A1 (n_49), .A2 (tx_data[14]), .ZN (n_16));
  CKND2D0 g4604__6260(.A1 (n_49), .A2 (tx_data[23]), .ZN (n_15));
  CKND2D0 g4611__4319(.A1 (n_49), .A2 (tx_data[22]), .ZN (n_12));
  CKND2D0 g4613__8428(.A1 (n_49), .A2 (transaction_length[0]), .ZN
       (n_11));
  CKND2D0 g4614__5526(.A1 (n_49), .A2 (n_145), .ZN (n_10));
  CKND0 g4577(.I (n_9), .ZN (n_134));
  NR2XD0 g4573__6783(.A1 (n_6), .A2 (chipADDRS[2]), .ZN (n_92));
  CKND2D1 g4575__3680(.A1 (n_8), .A2 (chipADDRS[2]), .ZN (n_52));
  IND2D1 g4576__1617(.A1 (chipADDRS[2]), .B1 (n_8), .ZN (n_13));
  CKND1 g4578(.I (n_88), .ZN (n_93));
  CKND0 g4626(.I (n_49), .ZN (n_122));
  AOI21D1 g4612__2802(.A1 (n_2), .A2 (spi_clk_main), .B (rst), .ZN
       (n_5));
  INVD1 g4625(.I (n_141), .ZN (n_4));
  NR2D0 g4617__1705(.A1 (n_143), .A2 (CPHA), .ZN (n_9));
  OR4D0 g4532__5122(.A1 (SPI_transaction_counter[4]), .A2
       (SPI_transaction_counter[0]), .A3 (SPI_transaction_counter[1]),
       .A4 (SPI_transaction_counter[2]), .Z (n_3));
  CKND2D1 g4622__8246(.A1 (n_22), .A2 (chipADDRS[0]), .ZN (n_6));
  ND3D1 g4618__7098(.A1 (SPI_state[1]), .A2 (SPI_state[0]), .A3
       (spi_clk_main), .ZN (n_88));
  OR2XD1 g4628__6131(.A1 (n_2), .A2 (SPI_state[0]), .Z (n_141));
  CKND0 g4621(.I (n_143), .ZN (busy));
  AN2XD1 g4629__1881(.A1 (n_2), .A2 (SPI_state[0]), .Z (n_49));
  NR2XD0 g4627__5115(.A1 (SPI_state[0]), .A2 (chipADDRS[0]), .ZN (n_8));
  NR2D0 g4624__7482(.A1 (SPI_state[1]), .A2 (SPI_state[0]), .ZN
       (n_143));
  CKND0 g4633(.I (rst), .ZN (n_1));
  CKND0 g4635(.I (chipADDRS[1]), .ZN (n_91));
  CKND0 g4636(.I (start_trans), .ZN (n_108));
  CKND0 g4634(.I (transaction_length[0]), .ZN (n_145));
  CKND0 g4637(.I (transaction_length[1]), .ZN (n_139));
  DFD1 \SPI_state_reg[0] (.CP (clk), .D (n_118), .Q (SPI_state[0]), .QN
       (n_22));
  DFCND1 spi_clk_main_reg(.CDN (n_1), .CP (ext_spi_clkx2), .D (n_0), .Q
       (spi_clk_main), .QN (n_0));
  DFKCND1 \SPI_state_reg[1] (.CP (clk), .CN (n_5), .D (SPI_state[0]),
       .Q (SPI_state[1]), .QN (n_2));
  IND2D1 g2(.A1 (n_13), .B1 (chipADDRS[1]), .ZN (n_193));
  IND2D1 g4757(.A1 (n_6), .B1 (chipADDRS[2]), .ZN (n_194));
endmodule

