
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May 23 2026 02:44:45 IST (May 22 2026 21:14:45 UTC)

// Verification Directory fv/SPI_Master_1 

module SPI_Master_1(i_Rst_L, i_Clk, i_TX_Byte, i_TX_DV, o_TX_Ready,
     o_RX_DV, o_RX_Byte, o_SPI_Clk, i_SPI_MISO, o_SPI_MOSI);
  input i_Rst_L, i_Clk, i_TX_DV, i_SPI_MISO;
  input [7:0] i_TX_Byte;
  output o_TX_Ready, o_RX_DV, o_SPI_Clk, o_SPI_MOSI;
  output [7:0] o_RX_Byte;
  wire i_Rst_L, i_Clk, i_TX_DV, i_SPI_MISO;
  wire [7:0] i_TX_Byte;
  wire o_TX_Ready, o_RX_DV, o_SPI_Clk, o_SPI_MOSI;
  wire [7:0] o_RX_Byte;
  wire [2:0] r_TX_Bit_Count;
  wire [7:0] r_TX_Byte;
  wire [2:0] r_RX_Bit_Count;
  wire [4:0] r_SPI_Clk_Edges;
  wire [1:0] r_SPI_Clk_Count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_93, n_94;
  wire r_Leading_Edge, r_TX_DV, r_Trailing_Edge;
  IOA21D1 g2268__2398(.A1 (o_SPI_MOSI), .A2 (o_TX_Ready), .B (n_79),
       .ZN (n_80));
  DFSNQD1 \r_TX_Bit_Count_reg[2] (.SDN (i_Rst_L), .CP (i_Clk), .D
       (n_78), .Q (r_TX_Bit_Count[2]));
  AOI32D1 g2269__5107(.A1 (r_TX_Byte[7]), .A2 (n_43), .A3 (r_TX_DV),
       .B1 (n_72), .B2 (n_77), .ZN (n_79));
  DFCNQD1 \o_RX_Byte_reg[2] (.CDN (i_Rst_L), .CP (i_Clk), .D (n_73), .Q
       (o_RX_Byte[2]));
  SDFCNQD1 \o_RX_Byte_reg[0] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (i_SPI_MISO), .SI (o_RX_Byte[0]), .SE (n_57), .Q (o_RX_Byte[0]));
  DFCNQD1 \o_RX_Byte_reg[6] (.CDN (i_Rst_L), .CP (i_Clk), .D (n_76), .Q
       (o_RX_Byte[6]));
  DFCNQD1 \o_RX_Byte_reg[4] (.CDN (i_Rst_L), .CP (i_Clk), .D (n_75), .Q
       (o_RX_Byte[4]));
  DFCNQD1 \o_RX_Byte_reg[5] (.CDN (i_Rst_L), .CP (i_Clk), .D (n_63), .Q
       (o_RX_Byte[5]));
  DFCNQD1 \o_RX_Byte_reg[7] (.CDN (i_Rst_L), .CP (i_Clk), .D (n_70), .Q
       (o_RX_Byte[7]));
  OAI211D1 g2271__6260(.A1 (r_TX_Bit_Count[2]), .A2 (n_71), .B (n_58),
       .C (n_77), .ZN (n_78));
  DFCNQD1 \o_RX_Byte_reg[3] (.CDN (i_Rst_L), .CP (i_Clk), .D (n_67), .Q
       (o_RX_Byte[3]));
  DFCNQD1 \o_RX_Byte_reg[1] (.CDN (i_Rst_L), .CP (i_Clk), .D (n_64), .Q
       (o_RX_Byte[1]));
  OAI21D1 g2285__4319(.A1 (n_74), .A2 (n_69), .B (n_61), .ZN (n_76));
  MOAI22D1 g2286__8428(.A1 (n_74), .A2 (n_62), .B1 (n_53), .B2
       (o_RX_Byte[4]), .ZN (n_75));
  MOAI22D1 g2290__5526(.A1 (n_74), .A2 (n_65), .B1 (n_55), .B2
       (o_RX_Byte[2]), .ZN (n_73));
  OAI221D0 g2272__6783(.A1 (n_2), .A2 (n_71), .B1 (r_Trailing_Edge),
       .B2 (n_0), .C (n_60), .ZN (n_72));
  OAI21D1 g2283__3680(.A1 (n_94), .A2 (n_69), .B (n_51), .ZN (n_70));
  DFCNQD1 o_RX_DV_reg(.CDN (i_Rst_L), .CP (i_Clk), .D (n_56), .Q
       (o_RX_DV));
  OAI211D1 g2287__1617(.A1 (n_47), .A2 (n_59), .B (n_71), .C (n_77),
       .ZN (n_68));
  OAI21D1 g2288__2802(.A1 (n_94), .A2 (n_65), .B (n_48), .ZN (n_67));
  MOAI22D1 g2289__1705(.A1 (n_94), .A2 (n_52), .B1 (n_46), .B2
       (o_RX_Byte[1]), .ZN (n_64));
  OAI21D1 g2282__5122(.A1 (n_94), .A2 (n_62), .B (n_50), .ZN (n_63));
  OAI21D1 g2296__8246(.A1 (n_54), .A2 (n_69), .B (o_RX_Byte[6]), .ZN
       (n_61));
  AOI33D1 g2297__7098(.A1 (n_12), .A2 (r_TX_Bit_Count[0]), .A3
       (r_Trailing_Edge), .B1 (n_1), .B2 (n_59), .B3
       (r_TX_Bit_Count[1]), .ZN (n_60));
  CKND2D1 g2284__6131(.A1 (n_71), .A2 (r_TX_Bit_Count[2]), .ZN (n_58));
  CKND1 g2301(.I (n_56), .ZN (n_57));
  SDFSNQD1 \r_TX_Bit_Count_reg[0] (.SDN (i_Rst_L), .CP (i_Clk), .D
       (o_TX_Ready), .SI (n_38), .SE (n_77), .Q (r_TX_Bit_Count[0]));
  OR2D1 g2302__1881(.A1 (n_54), .A2 (n_65), .Z (n_55));
  OR2D1 g2303__5115(.A1 (n_54), .A2 (n_62), .Z (n_53));
  NR2D1 g2305__7482(.A1 (n_54), .A2 (n_52), .ZN (n_56));
  OAI21D1 g2295__4733(.A1 (n_49), .A2 (n_69), .B (o_RX_Byte[7]), .ZN
       (n_51));
  CKND2D1 g2304__6161(.A1 (n_45), .A2 (i_SPI_MISO), .ZN (n_74));
  OAI21D1 g2292__9945(.A1 (n_49), .A2 (n_62), .B (o_RX_Byte[5]), .ZN
       (n_50));
  OAI21D1 g2294__2883(.A1 (n_49), .A2 (n_65), .B (o_RX_Byte[3]), .ZN
       (n_48));
  CKND2D1 g2306__2346(.A1 (n_59), .A2 (n_47), .ZN (n_71));
  OR2D1 g2298__1666(.A1 (n_49), .A2 (n_52), .Z (n_46));
  CKND1 g2309(.I (n_45), .ZN (n_54));
  OAI221D0 g2311__7410(.A1 (n_13), .A2 (r_Leading_Edge), .B1 (n_41),
       .B2 (r_RX_Bit_Count[0]), .C (n_43), .ZN (n_44));
  OAI221D0 g2315__6417(.A1 (n_9), .A2 (n_41), .B1 (r_Leading_Edge), .B2
       (n_8), .C (n_43), .ZN (n_42));
  OAI221D0 g2316__5477(.A1 (n_15), .A2 (n_41), .B1 (r_Leading_Edge),
       .B2 (n_14), .C (n_43), .ZN (n_40));
  NR2D1 g2325__2398(.A1 (r_TX_Bit_Count[0]), .A2 (n_37), .ZN (n_59));
  DFCNQD1 \r_SPI_Clk_Edges_reg[4] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (n_36), .Q (r_SPI_Clk_Edges[4]));
  CKXOR2D1 g2318__5107(.A1 (r_TX_Bit_Count[0]), .A2 (r_Trailing_Edge),
       .Z (n_38));
  NR3D0 g2312__6260(.A1 (r_RX_Bit_Count[0]), .A2 (n_41), .A3
       (o_TX_Ready), .ZN (n_45));
  DFCNQD1 \r_SPI_Clk_Edges_reg[3] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (n_32), .Q (r_SPI_Clk_Edges[3]));
  DFCNQD1 \r_SPI_Clk_Edges_reg[0] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (n_35), .Q (r_SPI_Clk_Edges[0]));
  DFCNQD1 \r_SPI_Clk_Edges_reg[1] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (n_33), .Q (r_SPI_Clk_Edges[1]));
  ND3D1 g2313__4319(.A1 (r_RX_Bit_Count[0]), .A2 (n_43), .A3
       (r_Leading_Edge), .ZN (n_49));
  DFCNQD1 r_SPI_Clk_reg(.CDN (i_Rst_L), .CP (i_Clk), .D (n_31), .Q
       (r_SPI_Clk_Count[1]));
  AO211D1 g2334__8428(.A1 (n_27), .A2 (r_SPI_Clk_Edges[4]), .B (n_93),
       .C (i_TX_DV), .Z (n_36));
  DFCNQD1 \r_SPI_Clk_Count_reg[0] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (n_29), .Q (r_SPI_Clk_Count[0]));
  NR2D1 g2328__5526(.A1 (n_23), .A2 (i_TX_DV), .ZN (n_35));
  NR2D1 g2332__6783(.A1 (n_26), .A2 (i_TX_DV), .ZN (n_34));
  NR2D1 g2333__3680(.A1 (n_25), .A2 (i_TX_DV), .ZN (n_33));
  NR2D1 g2331__1617(.A1 (n_24), .A2 (i_TX_DV), .ZN (n_32));
  MOAI22D1 g2317__2802(.A1 (n_30), .A2 (r_SPI_Clk_Count[1]), .B1
       (n_30), .B2 (r_SPI_Clk_Count[1]), .ZN (n_31));
  OA21D1 g2335__1705(.A1 (n_20), .A2 (r_SPI_Clk_Count[0]), .B (n_30),
       .Z (n_29));
  NR2XD0 g2338__5122(.A1 (r_TX_DV), .A2 (o_TX_Ready), .ZN (n_77));
  INR3D0 g2337__8246(.A1 (r_SPI_Clk_Count[1]), .B1 (i_TX_DV), .B2
       (n_27), .ZN (n_28));
  MAOI22D1 g2339__7098(.A1 (n_27), .A2 (r_SPI_Clk_Edges[2]), .B1
       (n_27), .B2 (n_10), .ZN (n_26));
  MAOI22D1 g2340__6131(.A1 (n_27), .A2 (r_SPI_Clk_Edges[1]), .B1
       (n_27), .B2 (n_7), .ZN (n_25));
  MAOI22D1 g2342__1881(.A1 (n_27), .A2 (r_SPI_Clk_Edges[3]), .B1
       (n_27), .B2 (n_16), .ZN (n_24));
  MAOI22D1 g2341__5115(.A1 (n_27), .A2 (r_SPI_Clk_Edges[0]), .B1
       (n_27), .B2 (r_SPI_Clk_Edges[0]), .ZN (n_23));
  NR3D0 g2336__4733(.A1 (n_27), .A2 (r_SPI_Clk_Count[1]), .A3
       (i_TX_DV), .ZN (n_21));
  ND2D1 g2346__6161(.A1 (n_20), .A2 (r_SPI_Clk_Count[0]), .ZN (n_30));
  ND2D1 g2347__9315(.A1 (n_18), .A2 (r_SPI_Clk_Count[0]), .ZN (n_27));
  NR2XD0 g2348__9945(.A1 (n_18), .A2 (i_TX_DV), .ZN (n_19));
  INR2D1 g2349__2883(.A1 (n_18), .B1 (i_TX_DV), .ZN (n_20));
  IND2D1 g2350__2346(.A1 (r_SPI_Clk_Edges[4]), .B1 (n_17), .ZN (n_18));
  AOI21D1 g2351__1666(.A1 (n_11), .A2 (r_SPI_Clk_Edges[3]), .B (n_17),
       .ZN (n_16));
  OA221D0 g2355__7410(.A1 (n_52), .A2 (r_RX_Bit_Count[0]), .B1 (n_14),
       .B2 (n_13), .C (n_69), .Z (n_15));
  MUX2ND0 g2356__6417(.I0 (n_5), .I1 (n_4), .S (r_TX_Bit_Count[2]), .ZN
       (n_12));
  NR2XD0 g2352__5477(.A1 (n_11), .A2 (r_SPI_Clk_Edges[3]), .ZN (n_17));
  OA21D1 g2353__2398(.A1 (n_6), .A2 (n_3), .B (n_11), .Z (n_10));
  SDFCNQD1 \r_TX_Byte_reg[2] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[2]), .SI (i_TX_Byte[2]), .SE (i_TX_DV), .Q
       (r_TX_Byte[2]));
  SDFCNQD1 \r_TX_Byte_reg[5] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[5]), .SI (i_TX_Byte[5]), .SE (i_TX_DV), .Q
       (r_TX_Byte[5]));
  SDFCNQD1 \r_TX_Byte_reg[3] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[3]), .SI (i_TX_Byte[3]), .SE (i_TX_DV), .Q
       (r_TX_Byte[3]));
  SDFCNQD1 \r_TX_Byte_reg[6] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[6]), .SI (i_TX_Byte[6]), .SE (i_TX_DV), .Q
       (r_TX_Byte[6]));
  SDFCNQD1 \r_TX_Byte_reg[0] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[0]), .SI (i_TX_Byte[0]), .SE (i_TX_DV), .Q
       (r_TX_Byte[0]));
  SDFCNQD1 \r_TX_Byte_reg[4] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[4]), .SI (i_TX_Byte[4]), .SE (i_TX_DV), .Q
       (r_TX_Byte[4]));
  AOI22D1 g2366__5107(.A1 (n_13), .A2 (n_8), .B1 (r_RX_Bit_Count[1]),
       .B2 (r_RX_Bit_Count[0]), .ZN (n_9));
  AOI21D1 g2365__6260(.A1 (r_SPI_Clk_Edges[1]), .A2
       (r_SPI_Clk_Edges[0]), .B (n_6), .ZN (n_7));
  OAI22D1 g2370__4319(.A1 (r_TX_Byte[1]), .A2 (r_TX_Bit_Count[1]), .B1
       (n_47), .B2 (r_TX_Byte[3]), .ZN (n_5));
  AOI22D1 g2369__8428(.A1 (n_47), .A2 (r_TX_Byte[5]), .B1
       (r_TX_Byte[7]), .B2 (r_TX_Bit_Count[1]), .ZN (n_4));
  SDFCNQD1 \r_TX_Byte_reg[1] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[1]), .SI (i_TX_Byte[1]), .SE (i_TX_DV), .Q
       (r_TX_Byte[1]));
  SDFCNQD1 \r_TX_Byte_reg[7] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_TX_Byte[7]), .SI (i_TX_Byte[7]), .SE (i_TX_DV), .Q
       (r_TX_Byte[7]));
  CKND2D1 g2354__5526(.A1 (n_6), .A2 (n_3), .ZN (n_11));
  MUX2ND0 g2367__6783(.I0 (r_TX_Byte[0]), .I1 (r_TX_Byte[4]), .S
       (r_TX_Bit_Count[2]), .ZN (n_2));
  MUX2D0 g2368__3680(.I0 (r_TX_Byte[2]), .I1 (r_TX_Byte[6]), .S
       (r_TX_Bit_Count[2]), .Z (n_1));
  CKND2D1 g2375__1617(.A1 (n_14), .A2 (n_8), .ZN (n_52));
  CKND2D1 g2376__2802(.A1 (n_8), .A2 (r_RX_Bit_Count[2]), .ZN (n_62));
  CKND2D1 g2377__1705(.A1 (n_14), .A2 (r_RX_Bit_Count[1]), .ZN (n_65));
  DFCNQD1 o_SPI_Clk_reg(.CDN (i_Rst_L), .CP (i_Clk), .D
       (r_SPI_Clk_Count[1]), .Q (o_SPI_Clk));
  DFCNQD1 r_TX_DV_reg(.CDN (i_Rst_L), .CP (i_Clk), .D (i_TX_DV), .Q
       (r_TX_DV));
  NR2XD0 g2374__5122(.A1 (r_SPI_Clk_Edges[1]), .A2
       (r_SPI_Clk_Edges[0]), .ZN (n_6));
  ND2D1 g2373__8246(.A1 (r_RX_Bit_Count[1]), .A2 (r_RX_Bit_Count[2]),
       .ZN (n_69));
  INR2D1 g2(.A1 (r_SPI_Clk_Edges[4]), .B1 (n_17), .ZN (n_93));
  DFCND1 r_Trailing_Edge_reg(.CDN (i_Rst_L), .CP (i_Clk), .D (n_28), .Q
       (r_Trailing_Edge), .QN (n_37));
  DFCND1 r_Leading_Edge_reg(.CDN (i_Rst_L), .CP (i_Clk), .D (n_21), .Q
       (r_Leading_Edge), .QN (n_41));
  DFCND1 o_TX_Ready_reg(.CDN (i_Rst_L), .CP (i_Clk), .D (n_19), .Q
       (o_TX_Ready), .QN (n_43));
  DFCND1 o_SPI_MOSI_reg(.CDN (i_Rst_L), .CP (i_Clk), .D (n_80), .Q
       (o_SPI_MOSI), .QN (n_0));
  DFCND1 \r_SPI_Clk_Edges_reg[2] (.CDN (i_Rst_L), .CP (i_Clk), .D
       (n_34), .Q (r_SPI_Clk_Edges[2]), .QN (n_3));
  DFSND1 \r_RX_Bit_Count_reg[0] (.SDN (i_Rst_L), .CP (i_Clk), .D
       (n_44), .Q (r_RX_Bit_Count[0]), .QN (n_13));
  DFSND1 \r_RX_Bit_Count_reg[2] (.SDN (i_Rst_L), .CP (i_Clk), .D
       (n_40), .Q (r_RX_Bit_Count[2]), .QN (n_14));
  DFSND1 \r_RX_Bit_Count_reg[1] (.SDN (i_Rst_L), .CP (i_Clk), .D
       (n_42), .Q (r_RX_Bit_Count[1]), .QN (n_8));
  DFSND1 \r_TX_Bit_Count_reg[1] (.SDN (i_Rst_L), .CP (i_Clk), .D
       (n_68), .Q (r_TX_Bit_Count[1]), .QN (n_47));
  IND2D1 g2438(.A1 (n_49), .B1 (i_SPI_MISO), .ZN (n_94));
endmodule

