
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May 23 2026 02:48:34 IST (May 22 2026 21:18:34 UTC)

// Verification Directory fv/spi_master_2 

module spi_master_2(rst_n, clk, tx_data, rx_data, wr_en, read, mode,
     baud_sel, tx_not_empty, rx_not_empty, request, spi_data_in,
     spi_clk, spi_data_out, cs_n);
  input rst_n, clk, wr_en, read, spi_data_in;
  input [7:0] tx_data;
  input [1:0] mode;
  input [2:0] baud_sel;
  output [7:0] rx_data;
  output tx_not_empty, rx_not_empty, request, spi_clk, spi_data_out,
       cs_n;
  wire rst_n, clk, wr_en, read, spi_data_in;
  wire [7:0] tx_data;
  wire [1:0] mode;
  wire [2:0] baud_sel;
  wire [7:0] rx_data;
  wire tx_not_empty, rx_not_empty, request, spi_clk, spi_data_out, cs_n;
  wire [5:0] brg_inst_cnt;
  wire [7:0] trans_buf;
  wire [3:0] state;
  wire [2:0] bit_cnt;
  wire [7:0] tx_buf;
  wire UNCONNECTED, brg_inst_ref_cpha_0, brg_inst_ref_cpha_1, n_0, n_1,
       n_3, n_4, n_5;
  wire n_6, n_7, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_20, n_21, n_22, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_94, n_95, strobe;
  DFCNQD1 \brg_inst_cnt_reg[5] (.CDN (rst_n), .CP (clk), .D (n_76), .Q
       (brg_inst_cnt[5]));
  NR4D0 g2404__2398(.A1 (n_75), .A2 (n_42), .A3 (n_6), .A4 (n_5), .ZN
       (n_77));
  NR2XD0 g2385__5107(.A1 (n_67), .A2 (n_60), .ZN (n_76));
  DFCNQD1 \trans_buf_reg[6] (.CDN (rst_n), .CP (clk), .D (n_62), .Q
       (trans_buf[6]));
  DFCNQD1 \trans_buf_reg[5] (.CDN (rst_n), .CP (clk), .D (n_69), .Q
       (trans_buf[5]));
  DFCNQD1 \trans_buf_reg[4] (.CDN (rst_n), .CP (clk), .D (n_59), .Q
       (trans_buf[4]));
  DFCNQD1 \brg_inst_cnt_reg[4] (.CDN (rst_n), .CP (clk), .D (n_61), .Q
       (brg_inst_cnt[4]));
  DFCNQD1 \trans_buf_reg[7] (.CDN (rst_n), .CP (clk), .D (n_74), .Q
       (spi_data_out));
  DFCNQD1 \trans_buf_reg[1] (.CDN (rst_n), .CP (clk), .D (n_68), .Q
       (trans_buf[1]));
  DFCNQD1 \trans_buf_reg[2] (.CDN (rst_n), .CP (clk), .D (n_64), .Q
       (trans_buf[2]));
  DFCNQD1 \trans_buf_reg[3] (.CDN (rst_n), .CP (clk), .D (n_65), .Q
       (trans_buf[3]));
  DFSNQD1 \state_reg[0] (.SDN (rst_n), .CP (clk), .D (n_63), .Q
       (state[0]));
  DFCNQD1 \trans_buf_reg[0] (.CDN (rst_n), .CP (clk), .D (n_73), .Q
       (trans_buf[0]));
  DFCNQD1 \state_reg[1] (.CDN (rst_n), .CP (clk), .D (n_55), .Q
       (state[1]));
  DFCNQD1 \bit_cnt_reg[1] (.CDN (rst_n), .CP (clk), .D (n_58), .Q
       (bit_cnt[1]));
  DFCNQD1 \bit_cnt_reg[2] (.CDN (rst_n), .CP (clk), .D (n_54), .Q
       (bit_cnt[2]));
  OAI211D1 g2436__6260(.A1 (n_41), .A2 (brg_inst_cnt[2]), .B (n_40), .C
       (n_11), .ZN (n_75));
  AO222D1 g2410__4319(.A1 (n_72), .A2 (trans_buf[6]), .B1 (n_71), .B2
       (spi_data_out), .C1 (n_70), .C2 (tx_buf[7]), .Z (n_74));
  AO222D1 g2411__8428(.A1 (n_72), .A2 (spi_data_in), .B1 (n_71), .B2
       (trans_buf[0]), .C1 (n_70), .C2 (tx_buf[0]), .Z (n_73));
  AO222D1 g2402__5526(.A1 (n_72), .A2 (trans_buf[4]), .B1 (n_71), .B2
       (trans_buf[5]), .C1 (n_70), .C2 (tx_buf[5]), .Z (n_69));
  AO222D1 g2412__6783(.A1 (n_72), .A2 (trans_buf[0]), .B1 (n_71), .B2
       (trans_buf[1]), .C1 (n_70), .C2 (tx_buf[1]), .Z (n_68));
  MAOI22D1 g2387__3680(.A1 (n_66), .A2 (brg_inst_cnt[5]), .B1 (n_66),
       .B2 (brg_inst_cnt[5]), .ZN (n_67));
  DFCNQD1 \brg_inst_cnt_reg[3] (.CDN (rst_n), .CP (clk), .D (n_53), .Q
       (brg_inst_cnt[3]));
  AO222D1 g2414__1617(.A1 (n_72), .A2 (trans_buf[2]), .B1 (n_71), .B2
       (trans_buf[3]), .C1 (n_70), .C2 (tx_buf[3]), .Z (n_65));
  AO222D1 g2413__2802(.A1 (n_72), .A2 (trans_buf[1]), .B1 (n_71), .B2
       (trans_buf[2]), .C1 (n_70), .C2 (tx_buf[2]), .Z (n_64));
  OAI222D0 g2426__1705(.A1 (n_34), .A2 (n_20), .B1 (tx_not_empty), .B2
       (n_32), .C1 (n_35), .C2 (wr_en), .ZN (n_63));
  AO222D1 g2415__5122(.A1 (n_72), .A2 (trans_buf[5]), .B1 (n_71), .B2
       (trans_buf[6]), .C1 (n_70), .C2 (tx_buf[6]), .Z (n_62));
  NR2XD0 g2388__8246(.A1 (n_49), .A2 (n_60), .ZN (n_61));
  AO222D1 g2403__7098(.A1 (n_72), .A2 (trans_buf[3]), .B1 (n_71), .B2
       (trans_buf[4]), .C1 (n_70), .C2 (tx_buf[4]), .Z (n_59));
  SDFCNQD1 \bit_cnt_reg[0] (.CDN (rst_n), .CP (clk), .D (n_57), .SI
       (n_56), .SE (bit_cnt[0]), .Q (bit_cnt[0]));
  DFCNQD1 brg_inst_ref_cpha_0_reg(.CDN (rst_n), .CP (clk), .D (n_52),
       .Q (brg_inst_ref_cpha_0));
  AO22D0 g2441__6131(.A1 (n_57), .A2 (n_3), .B1 (bit_cnt[1]), .B2
       (n_56), .Z (n_58));
  DFCNQD1 \state_reg[2] (.CDN (rst_n), .CP (clk), .D (n_46), .Q
       (state[2]));
  DFCNQD1 txne_reg(.CDN (rst_n), .CP (clk), .D (n_47), .Q
       (tx_not_empty));
  MOAI22D1 g2425__1881(.A1 (n_33), .A2 (n_36), .B1 (n_17), .B2
       (tx_not_empty), .ZN (n_55));
  AO22D0 g2427__5115(.A1 (n_57), .A2 (n_16), .B1 (bit_cnt[2]), .B2
       (n_56), .Z (n_54));
  DFCND1 busy_reg(.CDN (rst_n), .CP (clk), .D (n_44), .Q (UNCONNECTED),
       .QN (cs_n));
  DFCNQD1 \state_reg[3] (.CDN (rst_n), .CP (clk), .D (n_95), .Q
       (state[3]));
  NR2XD0 g2392__7482(.A1 (n_28), .A2 (n_60), .ZN (n_53));
  MOAI22D1 g2439__4733(.A1 (n_51), .A2 (brg_inst_ref_cpha_0), .B1
       (n_51), .B2 (brg_inst_ref_cpha_0), .ZN (n_52));
  SDFCNQD1 \rx_buf_reg[6] (.CDN (rst_n), .CP (clk), .D (rx_data[6]),
       .SI (trans_buf[5]), .SE (n_50), .Q (rx_data[6]));
  SDFCNQD1 \rx_buf_reg[1] (.CDN (rst_n), .CP (clk), .D (rx_data[1]),
       .SI (trans_buf[0]), .SE (n_50), .Q (rx_data[1]));
  SDFCNQD1 \rx_buf_reg[4] (.CDN (rst_n), .CP (clk), .D (rx_data[4]),
       .SI (trans_buf[3]), .SE (n_50), .Q (rx_data[4]));
  SDFCNQD1 \rx_buf_reg[3] (.CDN (rst_n), .CP (clk), .D (rx_data[3]),
       .SI (trans_buf[2]), .SE (n_50), .Q (rx_data[3]));
  DFCNQD1 \brg_inst_cnt_reg[2] (.CDN (rst_n), .CP (clk), .D (n_26), .Q
       (brg_inst_cnt[2]));
  DFCNQD1 done_reg(.CDN (rst_n), .CP (clk), .D (n_29), .Q (request));
  MAOI22D1 g2390__6161(.A1 (n_48), .A2 (brg_inst_cnt[4]), .B1 (n_48),
       .B2 (brg_inst_cnt[4]), .ZN (n_49));
  SDFCNQD1 \rx_buf_reg[2] (.CDN (rst_n), .CP (clk), .D (rx_data[2]),
       .SI (trans_buf[1]), .SE (n_50), .Q (rx_data[2]));
  SDFCNQD1 \rx_buf_reg[0] (.CDN (rst_n), .CP (clk), .D (rx_data[0]),
       .SI (spi_data_in), .SE (n_50), .Q (rx_data[0]));
  SDFCNQD1 \rx_buf_reg[7] (.CDN (rst_n), .CP (clk), .D (rx_data[7]),
       .SI (trans_buf[6]), .SE (n_50), .Q (rx_data[7]));
  SDFCNQD1 \rx_buf_reg[5] (.CDN (rst_n), .CP (clk), .D (rx_data[5]),
       .SI (trans_buf[4]), .SE (n_50), .Q (rx_data[5]));
  AO22D0 g2438__9315(.A1 (n_45), .A2 (tx_not_empty), .B1 (wr_en), .B2
       (n_43), .Z (n_47));
  OAI21D1 g2440__9945(.A1 (n_50), .A2 (n_37), .B (n_45), .ZN (n_46));
  ND2D1 g2435__2883(.A1 (n_24), .A2 (n_43), .ZN (n_44));
  IND2D1 g2391__2346(.A1 (n_48), .B1 (brg_inst_cnt[4]), .ZN (n_66));
  OAI211D1 g2450__1666(.A1 (n_41), .A2 (brg_inst_cnt[1]), .B (n_10), .C
       (n_4), .ZN (n_42));
  MOAI22D1 g2452__7410(.A1 (brg_inst_cnt[0]), .A2 (n_39), .B1
       (brg_inst_cnt[0]), .B2 (n_39), .ZN (n_40));
  DFCNQD1 \brg_inst_cnt_reg[1] (.CDN (rst_n), .CP (clk), .D (n_21), .Q
       (brg_inst_cnt[1]));
  MOAI22D1 g2453__5477(.A1 (n_12), .A2 (wr_en), .B1 (n_35), .B2 (n_31),
       .ZN (n_36));
  CKND2D1 g2444__2398(.A1 (n_33), .A2 (n_32), .ZN (n_34));
  NR2XD0 g2456__5107(.A1 (n_37), .A2 (n_25), .ZN (n_57));
  AN2XD1 g2447__6260(.A1 (n_33), .A2 (n_31), .Z (n_72));
  OAI21D1 g2463__4319(.A1 (n_1), .A2 (read), .B (n_32), .ZN (n_30));
  INR3D0 g2462__8428(.A1 (n_31), .B1 (cs_n), .B2 (n_35), .ZN (n_29));
  MAOI22D1 g2409__5526(.A1 (n_27), .A2 (brg_inst_cnt[3]), .B1 (n_27),
       .B2 (brg_inst_cnt[3]), .ZN (n_28));
  NR2XD0 g2428__6783(.A1 (n_14), .A2 (n_60), .ZN (n_26));
  INR2XD0 g2457__3680(.A1 (n_25), .B1 (n_37), .ZN (n_56));
  AO21D1 g2449__1617(.A1 (n_22), .A2 (n_31), .B (cs_n), .Z (n_24));
  DFCNQD1 \brg_inst_cnt_reg[0] (.CDN (rst_n), .CP (clk), .D (n_7), .Q
       (brg_inst_cnt[0]));
  CKND1 g2455(.I (n_45), .ZN (n_70));
  OAI21D1 g2454__2802(.A1 (n_22), .A2 (n_31), .B (strobe), .ZN (n_71));
  NR2XD0 g2464__1705(.A1 (n_94), .A2 (n_60), .ZN (n_21));
  CKND1 g2478(.I (n_37), .ZN (n_20));
  MOAI22D0 g2465__5122(.A1 (n_18), .A2 (mode[1]), .B1 (n_18), .B2
       (mode[1]), .ZN (spi_clk));
  CKND1 g2476(.I (n_32), .ZN (n_17));
  ND2D1 g2466__8246(.A1 (n_35), .A2 (strobe), .ZN (n_51));
  IND2D1 g2432__7098(.A1 (n_27), .B1 (brg_inst_cnt[3]), .ZN (n_48));
  MOAI22D1 g2451__6131(.A1 (n_15), .A2 (bit_cnt[2]), .B1 (n_15), .B2
       (bit_cnt[2]), .ZN (n_16));
  MAOI22D1 g2448__1881(.A1 (n_13), .A2 (brg_inst_cnt[2]), .B1 (n_13),
       .B2 (brg_inst_cnt[2]), .ZN (n_14));
  CKND2D1 g2460__5115(.A1 (n_12), .A2 (n_31), .ZN (n_45));
  NR2D0 g2459__7482(.A1 (n_12), .A2 (n_22), .ZN (n_33));
  INR3D0 g2467__4733(.A1 (bit_cnt[2]), .B1 (n_25), .B2 (n_15), .ZN
       (n_50));
  ND2D1 g2481__6161(.A1 (brg_inst_cnt[2]), .A2 (n_41), .ZN (n_11));
  ND2D1 g2480__9315(.A1 (brg_inst_cnt[1]), .A2 (n_41), .ZN (n_10));
  OAI31D0 g2482__9945(.A1 (baud_sel[1]), .A2 (baud_sel[2]), .A3
       (baud_sel[0]), .B (n_41), .ZN (n_39));
  IND3D1 g2485__2883(.A1 (state[2]), .B1 (state[3]), .B2 (n_9), .ZN
       (n_32));
  IND3D1 g2487__2346(.A1 (state[3]), .B1 (state[2]), .B2 (n_9), .ZN
       (n_37));
  SDFCNQD1 \tx_buf_reg[7] (.CDN (rst_n), .CP (clk), .D (tx_buf[7]), .SI
       (tx_data[7]), .SE (wr_en), .Q (tx_buf[7]));
  SDFCNQD1 \tx_buf_reg[0] (.CDN (rst_n), .CP (clk), .D (tx_buf[0]), .SI
       (tx_data[0]), .SE (wr_en), .Q (tx_buf[0]));
  SDFCNQD1 \tx_buf_reg[2] (.CDN (rst_n), .CP (clk), .D (tx_buf[2]), .SI
       (tx_data[2]), .SE (wr_en), .Q (tx_buf[2]));
  SDFCNQD1 \tx_buf_reg[1] (.CDN (rst_n), .CP (clk), .D (tx_buf[1]), .SI
       (tx_data[1]), .SE (wr_en), .Q (tx_buf[1]));
  SDFCNQD1 \tx_buf_reg[4] (.CDN (rst_n), .CP (clk), .D (tx_buf[4]), .SI
       (tx_data[4]), .SE (wr_en), .Q (tx_buf[4]));
  SDFCNQD1 \tx_buf_reg[5] (.CDN (rst_n), .CP (clk), .D (tx_buf[5]), .SI
       (tx_data[5]), .SE (wr_en), .Q (tx_buf[5]));
  SDFCNQD1 brg_inst_ref_cpha_1_reg(.CDN (rst_n), .CP (clk), .D
       (brg_inst_ref_cpha_1), .SI (brg_inst_ref_cpha_0), .SE (strobe),
       .Q (brg_inst_ref_cpha_1));
  NR2XD0 g2491__7410(.A1 (n_60), .A2 (brg_inst_cnt[0]), .ZN (n_7));
  SDFCNQD1 \tx_buf_reg[6] (.CDN (rst_n), .CP (clk), .D (tx_buf[6]), .SI
       (tx_data[6]), .SE (wr_en), .Q (tx_buf[6]));
  CKND1 g2477(.I (n_12), .ZN (n_43));
  SDFCNQD1 \tx_buf_reg[3] (.CDN (rst_n), .CP (clk), .D (tx_buf[3]), .SI
       (tx_data[3]), .SE (wr_en), .Q (tx_buf[3]));
  IND2D1 g2458__6417(.A1 (n_13), .B1 (brg_inst_cnt[2]), .ZN (n_27));
  INVD1 g2479(.I (n_22), .ZN (n_35));
  MAOI22D1 g2489__5477(.A1 (brg_inst_cnt[4]), .A2 (baud_sel[1]), .B1
       (brg_inst_cnt[4]), .B2 (baud_sel[1]), .ZN (n_6));
  MAOI22D1 g2490__2398(.A1 (brg_inst_cnt[5]), .A2 (baud_sel[2]), .B1
       (brg_inst_cnt[5]), .B2 (baud_sel[2]), .ZN (n_5));
  INR4D0 g2486__5107(.A1 (state[1]), .B1 (state[0]), .B2 (state[3]),
       .B3 (state[2]), .ZN (n_12));
  INR4D0 g2488__6260(.A1 (state[0]), .B1 (state[1]), .B2 (state[3]),
       .B3 (state[2]), .ZN (n_22));
  XNR2D1 g2494__4319(.A1 (brg_inst_cnt[3]), .A2 (baud_sel[0]), .ZN
       (n_4));
  CKXOR2D1 g2493__8428(.A1 (bit_cnt[1]), .A2 (bit_cnt[0]), .Z (n_3));
  MUX2D0 g2496__5526(.I0 (brg_inst_ref_cpha_0), .I1
       (brg_inst_ref_cpha_1), .S (mode[0]), .Z (n_18));
  ND3D0 g2492__6783(.A1 (baud_sel[2]), .A2 (baud_sel[0]), .A3
       (baud_sel[1]), .ZN (n_41));
  NR2XD0 g2502__3680(.A1 (n_0), .A2 (brg_inst_ref_cpha_0), .ZN (n_31));
  NR2XD0 g2497__1617(.A1 (state[1]), .A2 (state[0]), .ZN (n_9));
  OR2D1 g2501__2802(.A1 (cs_n), .A2 (strobe), .Z (n_60));
  CKND2D1 g2499__1705(.A1 (strobe), .A2 (brg_inst_ref_cpha_0), .ZN
       (n_25));
  CKND2D1 g2500__5122(.A1 (bit_cnt[1]), .A2 (bit_cnt[0]), .ZN (n_15));
  CKND2D1 g2498__8246(.A1 (brg_inst_cnt[0]), .A2 (brg_inst_cnt[1]), .ZN
       (n_13));
  XNR2D1 g2(.A1 (brg_inst_cnt[0]), .A2 (brg_inst_cnt[1]), .ZN (n_94));
  DFCND1 rxne_reg(.CDN (rst_n), .CP (clk), .D (n_30), .Q
       (rx_not_empty), .QN (n_1));
  DFCND1 brg_inst_clk_en_reg(.CDN (rst_n), .CP (clk), .D (n_77), .Q
       (strobe), .QN (n_0));
  INR2D1 g2554(.A1 (n_50), .B1 (n_37), .ZN (n_95));
endmodule

