
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May 23 2026 02:49:11 IST (May 22 2026 21:19:11 UTC)

// Verification Directory fv/spi_master_2 

module spi_master_2(rst_n, clk, tx_data, rx_data, wr_en, read, mode,
     baud_sel, tx_not_empty, rx_not_empty, request, spi_data_in,
     spi_clk, spi_data_out, cs_n);
  input rst_n, clk, wr_en, read, spi_data_in;
  input [7:0] tx_data;
  input [1:0] mode;
  input [2:0] baud_sel;
  output [7:0] rx_data;
  output tx_not_empty, rx_not_empty, request, spi_clk, spi_data_out,
       cs_n;
  wire rst_n, clk, wr_en, read, spi_data_in;
  wire [7:0] tx_data;
  wire [1:0] mode;
  wire [2:0] baud_sel;
  wire [7:0] rx_data;
  wire tx_not_empty, rx_not_empty, request, spi_clk, spi_data_out, cs_n;
  wire [5:0] brg_inst_cnt;
  wire [7:0] trans_buf;
  wire [3:0] state;
  wire [2:0] bit_cnt;
  wire [7:0] tx_buf;
  wire UNCONNECTED, brg_inst_ref_cpha_0, brg_inst_ref_cpha_1, n_0, n_1,
       n_3, n_4, n_5;
  wire n_6, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_20, n_21, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_94, n_95, strobe;
  DFCNQD1 \brg_inst_cnt_reg[5] (.CDN (rst_n), .CP (clk), .D (n_76), .Q
       (brg_inst_cnt[5]));
  NR4D0 g2348__2398(.A1 (n_73), .A2 (n_39), .A3 (n_5), .A4 (n_6), .ZN
       (n_77));
  NR2XD0 g2317__5107(.A1 (n_72), .A2 (n_74), .ZN (n_76));
  DFCNQD1 \trans_buf_reg[7] (.CDN (rst_n), .CP (clk), .D (n_69), .Q
       (spi_data_out));
  DFCNQD1 \trans_buf_reg[4] (.CDN (rst_n), .CP (clk), .D (n_60), .Q
       (trans_buf[4]));
  DFCNQD1 \trans_buf_reg[5] (.CDN (rst_n), .CP (clk), .D (n_61), .Q
       (trans_buf[5]));
  DFCNQD1 \brg_inst_cnt_reg[4] (.CDN (rst_n), .CP (clk), .D (n_75), .Q
       (brg_inst_cnt[4]));
  DFCNQD1 \trans_buf_reg[2] (.CDN (rst_n), .CP (clk), .D (n_63), .Q
       (trans_buf[2]));
  DFCNQD1 \trans_buf_reg[0] (.CDN (rst_n), .CP (clk), .D (n_65), .Q
       (trans_buf[0]));
  DFCNQD1 \trans_buf_reg[6] (.CDN (rst_n), .CP (clk), .D (n_70), .Q
       (trans_buf[6]));
  DFCNQD1 \trans_buf_reg[1] (.CDN (rst_n), .CP (clk), .D (n_64), .Q
       (trans_buf[1]));
  DFCNQD1 \trans_buf_reg[3] (.CDN (rst_n), .CP (clk), .D (n_62), .Q
       (trans_buf[3]));
  DFSNQD1 \state_reg[0] (.SDN (rst_n), .CP (clk), .D (n_58), .Q
       (state[0]));
  DFCNQD1 \bit_cnt_reg[2] (.CDN (rst_n), .CP (clk), .D (n_54), .Q
       (bit_cnt[2]));
  DFCNQD1 \state_reg[1] (.CDN (rst_n), .CP (clk), .D (n_59), .Q
       (state[1]));
  DFCNQD1 \bit_cnt_reg[1] (.CDN (rst_n), .CP (clk), .D (n_57), .Q
       (bit_cnt[1]));
  NR2XD0 g2320__6260(.A1 (n_49), .A2 (n_74), .ZN (n_75));
  OAI211D1 g2373__4319(.A1 (n_38), .A2 (brg_inst_cnt[2]), .B (n_35), .C
       (n_10), .ZN (n_73));
  MAOI22D1 g2319__8428(.A1 (n_71), .A2 (brg_inst_cnt[5]), .B1 (n_71),
       .B2 (brg_inst_cnt[5]), .ZN (n_72));
  SDFCNQD1 \bit_cnt_reg[0] (.CDN (rst_n), .CP (clk), .D (n_56), .SI
       (n_55), .SE (bit_cnt[0]), .Q (bit_cnt[0]));
  DFCNQD1 \brg_inst_cnt_reg[3] (.CDN (rst_n), .CP (clk), .D (n_47), .Q
       (brg_inst_cnt[3]));
  DFCNQD1 txne_reg(.CDN (rst_n), .CP (clk), .D (n_51), .Q
       (tx_not_empty));
  DFCNQD1 brg_inst_ref_cpha_0_reg(.CDN (rst_n), .CP (clk), .D (n_53),
       .Q (brg_inst_ref_cpha_0));
  AO222D1 g2357__5526(.A1 (n_68), .A2 (trans_buf[6]), .B1 (n_67), .B2
       (trans_buf[5]), .C1 (n_66), .C2 (tx_buf[6]), .Z (n_70));
  AO222D1 g2354__6783(.A1 (n_68), .A2 (spi_data_out), .B1 (n_67), .B2
       (trans_buf[6]), .C1 (n_66), .C2 (tx_buf[7]), .Z (n_69));
  AO222D1 g2355__3680(.A1 (n_68), .A2 (trans_buf[0]), .B1 (n_67), .B2
       (spi_data_in), .C1 (n_66), .C2 (tx_buf[0]), .Z (n_65));
  AO222D1 g2356__1617(.A1 (n_68), .A2 (trans_buf[1]), .B1 (n_67), .B2
       (trans_buf[0]), .C1 (n_66), .C2 (tx_buf[1]), .Z (n_64));
  AO222D1 g2353__2802(.A1 (n_68), .A2 (trans_buf[2]), .B1 (n_67), .B2
       (trans_buf[1]), .C1 (n_66), .C2 (tx_buf[2]), .Z (n_63));
  AO222D1 g2358__1705(.A1 (n_68), .A2 (trans_buf[3]), .B1 (n_67), .B2
       (trans_buf[2]), .C1 (n_66), .C2 (tx_buf[3]), .Z (n_62));
  AO222D1 g2346__5122(.A1 (n_68), .A2 (trans_buf[5]), .B1 (n_67), .B2
       (trans_buf[4]), .C1 (n_66), .C2 (tx_buf[5]), .Z (n_61));
  AO222D1 g2347__8246(.A1 (n_68), .A2 (trans_buf[4]), .B1 (n_67), .B2
       (trans_buf[3]), .C1 (n_66), .C2 (tx_buf[4]), .Z (n_60));
  MOAI22D1 g2367__7098(.A1 (n_45), .A2 (n_33), .B1 (n_20), .B2
       (tx_not_empty), .ZN (n_59));
  OAI221D0 g2368__6131(.A1 (n_44), .A2 (tx_not_empty), .B1 (wr_en), .B2
       (n_32), .C (n_46), .ZN (n_58));
  DFCNQD1 \state_reg[2] (.CDN (rst_n), .CP (clk), .D (n_37), .Q
       (state[2]));
  AO22D0 g2377__1881(.A1 (n_56), .A2 (n_3), .B1 (bit_cnt[1]), .B2
       (n_55), .Z (n_57));
  AO22D0 g2359__5115(.A1 (n_56), .A2 (n_15), .B1 (bit_cnt[2]), .B2
       (n_55), .Z (n_54));
  DFCNQD1 \state_reg[3] (.CDN (rst_n), .CP (clk), .D (n_95), .Q
       (state[3]));
  DFCND1 busy_reg(.CDN (rst_n), .CP (clk), .D (n_43), .Q (UNCONNECTED),
       .QN (cs_n));
  MOAI22D1 g2375__7482(.A1 (n_52), .A2 (brg_inst_ref_cpha_0), .B1
       (n_52), .B2 (brg_inst_ref_cpha_0), .ZN (n_53));
  AO22D0 g2376__4733(.A1 (n_36), .A2 (tx_not_empty), .B1 (wr_en), .B2
       (n_42), .Z (n_51));
  SDFCNQD1 \rx_buf_reg[3] (.CDN (rst_n), .CP (clk), .D (rx_data[3]),
       .SI (trans_buf[2]), .SE (n_50), .Q (rx_data[3]));
  SDFCNQD1 \rx_buf_reg[1] (.CDN (rst_n), .CP (clk), .D (rx_data[1]),
       .SI (trans_buf[0]), .SE (n_50), .Q (rx_data[1]));
  SDFCNQD1 \rx_buf_reg[0] (.CDN (rst_n), .CP (clk), .D (rx_data[0]),
       .SI (spi_data_in), .SE (n_50), .Q (rx_data[0]));
  SDFCNQD1 \rx_buf_reg[2] (.CDN (rst_n), .CP (clk), .D (rx_data[2]),
       .SI (trans_buf[1]), .SE (n_50), .Q (rx_data[2]));
  MAOI22D1 g2322__6161(.A1 (n_48), .A2 (brg_inst_cnt[4]), .B1 (n_48),
       .B2 (brg_inst_cnt[4]), .ZN (n_49));
  DFCNQD1 done_reg(.CDN (rst_n), .CP (clk), .D (n_26), .Q (request));
  NR2XD0 g2328__9315(.A1 (n_28), .A2 (n_74), .ZN (n_47));
  SDFCNQD1 \rx_buf_reg[4] (.CDN (rst_n), .CP (clk), .D (rx_data[4]),
       .SI (trans_buf[3]), .SE (n_50), .Q (rx_data[4]));
  SDFCNQD1 \rx_buf_reg[5] (.CDN (rst_n), .CP (clk), .D (rx_data[5]),
       .SI (trans_buf[4]), .SE (n_50), .Q (rx_data[5]));
  SDFCNQD1 \rx_buf_reg[7] (.CDN (rst_n), .CP (clk), .D (rx_data[7]),
       .SI (trans_buf[6]), .SE (n_50), .Q (rx_data[7]));
  SDFCNQD1 \rx_buf_reg[6] (.CDN (rst_n), .CP (clk), .D (rx_data[6]),
       .SI (trans_buf[5]), .SE (n_50), .Q (rx_data[6]));
  DFCNQD1 \brg_inst_cnt_reg[2] (.CDN (rst_n), .CP (clk), .D (n_31), .Q
       (brg_inst_cnt[2]));
  ND3D1 g2374__9945(.A1 (n_45), .A2 (n_44), .A3 (n_40), .ZN (n_46));
  ND2D1 g2372__2883(.A1 (n_23), .A2 (n_42), .ZN (n_43));
  DFCNQD1 \brg_inst_cnt_reg[1] (.CDN (rst_n), .CP (clk), .D (n_21), .Q
       (brg_inst_cnt[1]));
  OAI211D1 g2385__1666(.A1 (n_38), .A2 (brg_inst_cnt[1]), .B (n_11), .C
       (n_4), .ZN (n_39));
  OAI21D1 g2340__7410(.A1 (n_50), .A2 (n_40), .B (n_36), .ZN (n_37));
  MOAI22D1 g2383__6417(.A1 (brg_inst_cnt[0]), .A2 (n_34), .B1
       (brg_inst_cnt[0]), .B2 (n_34), .ZN (n_35));
  IND2D1 g2332__5477(.A1 (n_48), .B1 (brg_inst_cnt[4]), .ZN (n_71));
  MOAI22D1 g2386__2398(.A1 (n_13), .A2 (wr_en), .B1 (n_32), .B2 (n_30),
       .ZN (n_33));
  NR2XD0 g2369__5107(.A1 (n_17), .A2 (n_74), .ZN (n_31));
  IOA21D1 g2388__6260(.A1 (n_32), .A2 (n_25), .B (strobe), .ZN (n_68));
  AN2XD1 g2382__4319(.A1 (n_45), .A2 (n_30), .Z (n_67));
  OAI21D1 g2395__8428(.A1 (n_1), .A2 (read), .B (n_44), .ZN (n_29));
  MAOI22D1 g2360__5526(.A1 (n_27), .A2 (brg_inst_cnt[3]), .B1 (n_27),
       .B2 (brg_inst_cnt[3]), .ZN (n_28));
  NR3D0 g2398__6783(.A1 (n_32), .A2 (n_25), .A3 (cs_n), .ZN (n_26));
  NR2XD0 g2391__3680(.A1 (n_40), .A2 (n_24), .ZN (n_56));
  INR2XD0 g2392__1617(.A1 (n_24), .B1 (n_40), .ZN (n_55));
  AO21D1 g2379__2802(.A1 (n_12), .A2 (n_30), .B (cs_n), .Z (n_23));
  IND2D1 g2370__1705(.A1 (n_27), .B1 (brg_inst_cnt[3]), .ZN (n_48));
  DFCNQD1 \brg_inst_cnt_reg[0] (.CDN (rst_n), .CP (clk), .D (n_8), .Q
       (brg_inst_cnt[0]));
  NR2XD0 g2396__5122(.A1 (n_94), .A2 (n_74), .ZN (n_21));
  CKND1 g2408(.I (n_44), .ZN (n_20));
  MOAI22D0 g2397__8246(.A1 (n_18), .A2 (mode[1]), .B1 (n_18), .B2
       (mode[1]), .ZN (spi_clk));
  ND2D1 g2399__7098(.A1 (n_32), .A2 (strobe), .ZN (n_52));
  CKND1 g2389(.I (n_66), .ZN (n_36));
  MAOI22D1 g2387__6131(.A1 (n_16), .A2 (brg_inst_cnt[2]), .B1 (n_16),
       .B2 (brg_inst_cnt[2]), .ZN (n_17));
  MOAI22D1 g2384__1881(.A1 (n_14), .A2 (bit_cnt[2]), .B1 (n_14), .B2
       (bit_cnt[2]), .ZN (n_15));
  NR2D0 g2390__5115(.A1 (n_13), .A2 (n_12), .ZN (n_45));
  AN2XD1 g2394__7482(.A1 (n_13), .A2 (n_30), .Z (n_66));
  INR3D0 g2371__4733(.A1 (bit_cnt[2]), .B1 (n_14), .B2 (n_24), .ZN
       (n_50));
  ND2D1 g2412__6161(.A1 (brg_inst_cnt[1]), .A2 (n_38), .ZN (n_11));
  ND2D1 g2411__9315(.A1 (brg_inst_cnt[2]), .A2 (n_38), .ZN (n_10));
  OAI31D0 g2414__9945(.A1 (baud_sel[1]), .A2 (baud_sel[2]), .A3
       (baud_sel[0]), .B (n_38), .ZN (n_34));
  IND3D1 g2416__2883(.A1 (state[2]), .B1 (state[3]), .B2 (n_9), .ZN
       (n_44));
  IND3D1 g2417__2346(.A1 (state[3]), .B1 (state[2]), .B2 (n_9), .ZN
       (n_40));
  SDFCNQD1 \tx_buf_reg[6] (.CDN (rst_n), .CP (clk), .D (tx_buf[6]), .SI
       (tx_data[6]), .SE (wr_en), .Q (tx_buf[6]));
  SDFCNQD1 \tx_buf_reg[5] (.CDN (rst_n), .CP (clk), .D (tx_buf[5]), .SI
       (tx_data[5]), .SE (wr_en), .Q (tx_buf[5]));
  SDFCNQD1 \tx_buf_reg[3] (.CDN (rst_n), .CP (clk), .D (tx_buf[3]), .SI
       (tx_data[3]), .SE (wr_en), .Q (tx_buf[3]));
  SDFCNQD1 \tx_buf_reg[1] (.CDN (rst_n), .CP (clk), .D (tx_buf[1]), .SI
       (tx_data[1]), .SE (wr_en), .Q (tx_buf[1]));
  SDFCNQD1 \tx_buf_reg[0] (.CDN (rst_n), .CP (clk), .D (tx_buf[0]), .SI
       (tx_data[0]), .SE (wr_en), .Q (tx_buf[0]));
  SDFCNQD1 \tx_buf_reg[2] (.CDN (rst_n), .CP (clk), .D (tx_buf[2]), .SI
       (tx_data[2]), .SE (wr_en), .Q (tx_buf[2]));
  SDFCNQD1 brg_inst_ref_cpha_1_reg(.CDN (rst_n), .CP (clk), .D
       (brg_inst_ref_cpha_1), .SI (brg_inst_ref_cpha_0), .SE (strobe),
       .Q (brg_inst_ref_cpha_1));
  NR2XD0 g2422__1666(.A1 (n_74), .A2 (brg_inst_cnt[0]), .ZN (n_8));
  CKND1 g2409(.I (n_13), .ZN (n_42));
  SDFCNQD1 \tx_buf_reg[4] (.CDN (rst_n), .CP (clk), .D (tx_buf[4]), .SI
       (tx_data[4]), .SE (wr_en), .Q (tx_buf[4]));
  INVD1 g2431(.I (n_30), .ZN (n_25));
  SDFCNQD1 \tx_buf_reg[7] (.CDN (rst_n), .CP (clk), .D (tx_buf[7]), .SI
       (tx_data[7]), .SE (wr_en), .Q (tx_buf[7]));
  IND2D1 g2393__6417(.A1 (n_16), .B1 (brg_inst_cnt[2]), .ZN (n_27));
  INVD1 g2410(.I (n_12), .ZN (n_32));
  MAOI22D1 g2420__5477(.A1 (brg_inst_cnt[5]), .A2 (baud_sel[2]), .B1
       (brg_inst_cnt[5]), .B2 (baud_sel[2]), .ZN (n_6));
  MAOI22D1 g2421__2398(.A1 (brg_inst_cnt[4]), .A2 (baud_sel[1]), .B1
       (brg_inst_cnt[4]), .B2 (baud_sel[1]), .ZN (n_5));
  INR4D0 g2419__5107(.A1 (state[0]), .B1 (state[1]), .B2 (state[3]),
       .B3 (state[2]), .ZN (n_12));
  INR4D0 g2418__6260(.A1 (state[1]), .B1 (state[0]), .B2 (state[3]),
       .B3 (state[2]), .ZN (n_13));
  XNR2D1 g2425__4319(.A1 (brg_inst_cnt[3]), .A2 (baud_sel[0]), .ZN
       (n_4));
  CKXOR2D1 g2424__8428(.A1 (bit_cnt[1]), .A2 (bit_cnt[0]), .Z (n_3));
  MUX2D0 g2427__5526(.I0 (brg_inst_ref_cpha_0), .I1
       (brg_inst_ref_cpha_1), .S (mode[0]), .Z (n_18));
  ND3D0 g2423__6783(.A1 (baud_sel[2]), .A2 (baud_sel[1]), .A3
       (baud_sel[0]), .ZN (n_38));
  NR2XD0 g2434__3680(.A1 (n_0), .A2 (brg_inst_ref_cpha_0), .ZN (n_30));
  CKND2D1 g2429__1617(.A1 (strobe), .A2 (brg_inst_ref_cpha_0), .ZN
       (n_24));
  CKND2D1 g2433__2802(.A1 (bit_cnt[1]), .A2 (bit_cnt[0]), .ZN (n_14));
  NR2XD0 g2428__1705(.A1 (state[1]), .A2 (state[0]), .ZN (n_9));
  CKND2D1 g2432__5122(.A1 (brg_inst_cnt[0]), .A2 (brg_inst_cnt[1]), .ZN
       (n_16));
  OR2D1 g2430__8246(.A1 (cs_n), .A2 (strobe), .Z (n_74));
  XNR2D1 g2(.A1 (brg_inst_cnt[0]), .A2 (brg_inst_cnt[1]), .ZN (n_94));
  DFCND1 rxne_reg(.CDN (rst_n), .CP (clk), .D (n_29), .Q
       (rx_not_empty), .QN (n_1));
  DFCND1 brg_inst_clk_en_reg(.CDN (rst_n), .CP (clk), .D (n_77), .Q
       (strobe), .QN (n_0));
  INR2D1 g2486(.A1 (n_50), .B1 (n_40), .ZN (n_95));
endmodule

